### ISSUE TITLE
CSS is not rendered on HTTPS site.

### ISSUE THREAD

**Issue by gaganchandan** [academicpages/academicpages.github.io#1010]
I was using a custom domain for my site. Recently, I enforced HTTPS and now the CSS does not work anymore. What can I do to fix this?

**Comment by crusher083** [comment]
The same for me, here's error log I got after running it locally:
```
2022-08-23 10:14:09] ERROR NoMethodError: undefined method `key?' for nil:NilClass
        /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve/servlet.rb:191:in `conditionally_inject_charset'
        /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve/servlet.rb:176:in `do_GET'
        /Library/Ruby/Gems/2.6.0/gems/hawkins-2.0.5/lib/hawkins/servlet.rb:134:in `do_GET'
        /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/webrick/httpservlet/abstract.rb:105:in `service'
        /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/webrick/httpservlet/filehandler.rb:233:in `service'
        /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/webrick/httpserver.rb:140:in `service'
        /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/webrick/httpserver.rb:96:in `run'
        /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/webrick/server.rb:307:in `block in start_thread'
```

**Comment by gaganchandan** [comment]
@valentynbez I fixed my problem by changing all occurrences of HTTP in the code to HTTPS.

**Comment by MKLOL** [comment]
> The same for me, here's error log I got after running it locally:
> 
> ```
> [2022-08-23 10:14:09] ERROR NoMethodError: undefined method `key?' for nil:NilClass
>         /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve/servlet.rb:191:in `conditionally_inject_charset'
>         /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve/servlet.rb:176:in `do_GET'
>         /Library/Ruby/Gems/2.6.0/gems/hawkins-2.0.5/lib/hawkins/servlet.rb:134:in `do_GET'
>         /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/webrick/httpservlet/abstract.rb:105:in `service'
>         /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/webrick/httpservlet/filehandler.rb:233:in `service'
>         /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/webrick/httpserver.rb:140:in `service'
>         /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/webrick/httpserver.rb:96:in `run'
>         /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/webrick/server.rb:307:in `block in start_thread'
> ```

Your problem is different @valentynbez  https://github.com/academicpages/academicpages.github.io/issues/1032#issuecomment-1271084019
