### ISSUE TITLE
Theme is not rendering

### ISSUE THREAD

**Issue by ehosseiniasl** [academicpages/academicpages.github.io#1041]
Hello,

I clone your repo, and change the "url" and "repository" in _config.yml file, and configured jekyll.

repository: https://github.com/ehosseiniasl/my-website.github.io

However, the website them is not rendering, see below

<img width="1096" alt="Screen Shot 2022-10-05 at 2 47 54 PM" src="https://user-images.githubusercontent.com/6238049/194170437-4ca6daf5-5696-4d6b-91e6-b61c441af479.png">

**Comment by ehosseiniasl** [comment]
I added `theme: minima` and still theme is not rendered.
can someone help me?

**Comment by ehosseiniasl** [comment]
@hainesr @Carreau @qaisjp @bxie

**Comment by gegewen** [comment]
I am having the same issue here. Any solutions?

**Comment by JunnanDong** [comment]
@gegewen try not to directly replace all the content in one file, filling it one by one with manual inputs

**Comment by dddraxxx** [comment]
Same issue here. Is there any solution?

**Comment by dddraxxx** [comment]
I found the solution. Change base_path file to
```
{% if site.url and site.url contains "localhost" %}
  {% assign base_path = "" | append: site.baseurl %}
{% elsif site.url %}
  {% assign base_path = site.url | append: site.baseurl %}
{% else %}
  {% assign base_path = site.github.url %}
{% endif %}
```

**Comment by darthbhyrava** [comment]
Same issue, ^ the above solution doesn't work. Any leads?

**Comment by faithless426** [comment]
Having the same issue, anyone found a fix?

**Comment by vincentcaiwu** [comment]
Same issue. Did anyone figure out how to fix it?

**Comment by rjzupkoii** [comment]
This might have been corrected with the latest fixes.

**Comment by rjzupkoii** [comment]
If `minima` is a Jekyll theme then that might be the cause of the problem since Academic Pages is  its own theme, also you may want take a look at #1919 since MathJax can interfere with rendering, although the "stock" template is now working with MathJax.
