### ISSUE TITLE
What is the difference between collection and category in this repo?

### ISSUE THREAD

**Issue by szrlee** [academicpages/academicpages.github.io#107]
I see in the historical commits, one change category to the collection. and collection is used to determine how to render a page. therefore, I wonder what is the use of category now?

Thank you!

**Comment by szrlee** [comment]
Actually, another question should also be raised: the difference between tags and categories?

Also, is it possible to use tags or categories to classify the publication and 
let readers find certain papers according to some tags shown remarkably at some places in the page?

**Comment by hiraksarkar** [comment]
Still interested in this !!

**Comment by rjzupkoii** [comment]
I've updated the wiki to include [some commentary on this](https://github.com/academicpages/academicpages.github.io/wiki/Customizing-the-content-on-your-site#collections-and-categories), but category is still used to render blog posts.
