### ISSUE TITLE
The website cannot render in the edge browser

### ISSUE THREAD

**Issue by JhengLu** [academicpages/academicpages.github.io#1151]
When I committed, the website looks different in the Edge browser and in the Chrome browser, I only change the _config.yml, can anyone help me with it?
![image](https://user-images.githubusercontent.com/77672985/213184896-0ad1d457-b6bb-47a1-8981-f9adee56868e.png)
![image](https://user-images.githubusercontent.com/77672985/213185092-7262c070-4681-4451-933f-aa3b283ff46d.png)

**Comment by vincentcaiwu** [comment]
Hi, same issue here. Have you fixed it now? If so, it will be of great help if you could tell me the solution. Thanks!

**Comment by rjzupkoii** [comment]
The latest updates might have fixed this as I'm unable to reproduce the error on Edge.
