### ISSUE TITLE
how to enable indexing by search engine

### ISSUE THREAD

**Issue by glhfgg1024** [academicpages/academicpages.github.io#116]
Hi thanks for your great work! 
I have a question, how to enable the webpage indexed by search engine? Thanks.

**Comment by rjzupkoii** [comment]
Once the website has been deployed, it make take a bit of time, but most search engines should index it automatically. If you want to help speed up the process a bit, updating your GitHub user page to include a link to your Academic Pages github.io website should help the web crawlers find it a bit faster.
