### ISSUE TITLE
Local running on windows 10: Unable to load the EventMachine C extension

### ISSUE THREAD

**Issue by anubrata** [academicpages/academicpages.github.io#117]
While trying to run locally using 
`bundle exec jekyll serve`

getting the following error

`Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.7-x64-mingw32/lib/rubyeventmachine.rb:2:in `require': cannot load such file -- 2.4/rubyeventmachine (LoadError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.7-x64-mingw32/lib/rubyeventmachine.rb:2:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.7-x64-mingw32/lib/eventmachine.rb:8:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.7-x64-mingw32/lib/eventmachine.rb:8:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/em-websocket-0.5.1/lib/em-websocket.rb:3:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/em-websocket-0.5.1/lib/em-websocket.rb:3:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/hawkins-2.0.5/lib/hawkins/websockets.rb:2:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/hawkins-2.0.5/lib/hawkins/websockets.rb:2:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/hawkins-2.0.5/lib/hawkins.rb:8:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/hawkins-2.0.5/lib/hawkins.rb:8:in `<module:Hawkins>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/hawkins-2.0.5/lib/hawkins.rb:3:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:81:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:76:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:76:in `block in require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:65:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:65:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.2/lib/bundler.rb:114:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.3/lib/jekyll/plugin_manager.rb:51:in `require_from_bundler'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.7.3/exe/jekyll:11:in `<top (required)>'
        from C:/Ruby24-x64/bin/jekyll:23:in `load'
        from C:/Ruby24-x64/bin/jekyll:23:in `<main>'`

**Comment by ELHAMLAOUI** [comment]
Hello,
Is there any tips for this problem ?

**Comment by ELHAMLAOUI** [comment]
gem uninstall eventmachine
gem install eventmachine --platform ruby
For more details https://github.com/oneclick/rubyinstaller2/issues/96

**Comment by sigma67** [comment]
For me only `gem uninstall eventmachine --force` worked.

**Comment by mtrussell** [comment]
For me, running:
```
gem uninstall eventmachine
gem install eventmachine --platform ruby
```
works only temporarily.

I still get the error 'Unable to load the EventMachine C extension' at least once every day or so. This is true if I'm working on only one project for a few days in a row or switching between different projects.

Does anybody know of a more permanent solution to this?

For reference, I'm using:
Windows 10 v2004
Ruby 2.6.5p114
Rails 6.0.3.4

**Comment by rjzupkoii** [comment]
Given the updates to the libraries since this was opened, I'm going to go ahead and close since too much time has past.
