### ISSUE TITLE
Anyway to speed up the web page updates?

### ISSUE THREAD

**Issue by TsingQAQ** [academicpages/academicpages.github.io#119]
Hi there thanks for this wonderful tool while I was a little bit puzzled by the relative long updating period of the web pages, every time I've committed a code change I have to wait for at 1 minutes or 2 to see the outcome pages. This situation becomes much more annoying if the changes is more frequent.
I wonder if there are some instructions that can make the academic pages refresh right after the submission?
Thanks in advance

**Comment by yingjun-mou** [comment]
Hi @TsingQAQ , I am having the same issue. Wondering have you solved the issue?

**Comment by TsingQAQ** [comment]
Hi @yingjun-mou, not really on its own, but maybe one way to work around can be making modifications/debugging offline (e.g., in a web dev IDE), which is able to check it much faster. You can later submit the satisfying version on your forked repo.

**Comment by yingjun-mou** [comment]
Got it, I will try that. Thank you @TsingQAQ for your prompt reply!
