### ISSUE TITLE
Add "Read more" to year-archive

### ISSUE THREAD

**Issue by alex-konovalov** [academicpages/academicpages.github.io#12]
First, thank you for your work and sharing this - very nice template! 

Second, is there a way to add "Read more" to the posts which are not fully displayed e.g. at `year-archive` page like https://alex-konovalov.github.io/year-archive/ ? 

I've found some suggestions at https://blog.omgmog.net/post/adding-support-for-more-tag-to-jekyll-without-plugins/ but I am not familiar with academicpages.github.io yet, so it's not clear for me if this will work.

**Comment by staeiou** [comment]
Hi @alex-konovalov, apologies for the long delay. I've added this in PR #29, with a variable in _config.yml that enables/disables "read more" links for everything with an excerpt. [This is the diff](https://github.com/academicpages/academicpages.github.io/compare/8f859e7ef84125a6442348044d12922d20e961f5...78167c4) of the code changed.

**Comment by alex-konovalov** [comment]
Great, thanks @staeiou ! I will try to pull latest changes to the template when I will be next updating my site.

**Comment by alex-konovalov** [comment]
@staeiou thanks, works well for me!
