### ISSUE TITLE
Problem with gemfiles and profile picture

### ISSUE THREAD

**Issue by omarvd** [academicpages/academicpages.github.io#1222]
Hi colleagues,

I hope you are doing well.

My academic website was running perfectly, but yesterday it stopped showing my profile picture. This happened after I linked the repository with Netlify. My repository is [here](https://github.com/omarvd/omarvd.github.io).

This is the error I get.

build
github-pages can't satisfy your Gemfile's dependencies.

I've been trying to fix this for quite a while, with no success. I would really appreciate it if someone could help me find what's going on.

Many thanks,
Omar

**Comment by MenHimChan** [comment]
Experiencing the same problem....

**Comment by rjzupkoii** [comment]
This might be related in someway to #1902 which should now be fixed.
