### ISSUE TITLE
Using newer version of academicicons?

### ISSUE THREAD

**Issue by esselltwo** [academicpages/academicpages.github.io#127]
I wanted to include my MathOverflow profile in my sidebar. Luckily there is a version of the logo in the newest (1.8.6) version of Academicicons. However, doing the obvious thing, which is copying the updated Academicicons files into `assets/css` and `assets/fonts` and adding
````
{% if author.mathoverflow %}
    <li><a href="http://mathoverflow.net/users/{{ author.mathoverflow }}"><i class="ai ai-mathoverflow-square"></i> MathOverflow</a></li>
{% endif %}
````
to `_includes/author-profile.html` doesn't seem to work. The link shows up fine, but the icon doesn't.

**Comment by stevenov** [comment]
I have a similar question. I'd like to use a Mastodon logo but it doesn't seem to be pulling from the current fontawesome

**Comment by nilsanilsson** [comment]
I am trying to do something like this. I want to add my InspireHEP handle to the sidebar, and it seems to be avaiable from academicicons, but it is not showing up. Does anyone know of a solution?

**Comment by Tom-Dee** [comment]
Now that the #TwitterMigration is happening, it'd be great to include a #Mastodon icon among the social-media links and to do so with the <a rel="me"...> feature that allows for #Mastodon verification.

**Comment by rjzupkoii** [comment]
This appears to have been addressed, and Mastodon icon has been added to the template as well.

**Comment by stevenov** [comment]
I'm not seeing the icon after updating _config.yml, author-profile.html, _utilities, and _variables. Is it something I'm doing? Or not doing?

**Comment by rjzupkoii** [comment]
@stevenov How did you update the files? Do they have the same changes as 066dc22?

**Comment by stevenov** [comment]
I downloaded the two .scss files into my local repo and copy-and-pasted the if-author.mastodon line into my existing author-profile.html, and then I pushed everything. You can see my Mastodon link; just no icon. Thanks!

**Comment by rjzupkoii** [comment]
@stevenov There was an update to the font library as well at f776953, try adding that and see if it works.

**Comment by stevenov** [comment]
I downloaded the new _syntax.scss into my repo and pushed, but still no icon.

**Comment by rjzupkoii** [comment]
@stevenov Since there's been quite a few updates in the past couple days it's quite likely that I'm blanking on which one you would need, however the icon is working as expected with the stock template so it's hard for me to say what might be going on without taking a closer look at your code. You might want to start a thread over in the discussion since that should get more attention - as it is I'm the only one that gets notifications on updated to closed issues.
