### ISSUE TITLE
HTTPS with Custom Domain

### ISSUE THREAD

**Issue by hammadshaikhha** [academicpages/academicpages.github.io#129]
I recently tried to move my custom domain website from http to https, but I ran into the problem of google chrome blocking the scripts from loading. On github pages it is recommends changing the html files from http to https (https://help.github.com/articles/securing-your-github-pages-site-with-https/).

Has this repo already been updated so that it is compatible with the new https with custom domain?

**Comment by staeiou** [comment]
Hi, the repo should support https by default, as long as the `url` parameter in `_config.yml` begins with `https://`, although this should be your custom domain, not your github.io URL.  All links and included scripts are defined relative to that base URL path. It seems like you've got your github.io URL, and there's something possibly in the cross-site scripting making that fall back to http, even though viewing the HTML source shows those scripts are https. 

But then in my experience, I also had to use Cloudflare's free DNS to get https working on my custom domain. [This article](https://blog.yechiel.me/adding-https-to-github-pages-using-a-custom-domain-7e4ee8ab1c50) is a good intro to that.

**Comment by staeiou** [comment]
Also, I see that cloudflare post is listed as out of date, and they suggest using the "force HTTPS" option in the GitHub pages setting in the repo's setting tab. The cloudflare option is still working for my own site without using the new force HTTPS option, so that's still possible as a fallback.

**Comment by hammadshaikhha** [comment]
Thank you for the reply, problem has been solved! I just changed the url in _config.yml to by custom domain with https instead of the old github.io. I have custom domain with https now, loading fine, thanks!
