### ISSUE TITLE
Mobile version of website not visualizing correctly when using custom domain

### ISSUE THREAD

**Issue by sam-a-levy** [academicpages/academicpages.github.io#1294]
I set a custom domain for my page, following the steps outlined [here](https://medium.com/8px-magazine/hosting-a-website-for-free-get-started-with-google-domains-github-pages-980986550958) and since then I have found that while everything appears correct on the desktop version of my page [sam-a-levy.com](https://sam-a-levy.com/) (github [here](https://github.com/sam-a-levy/sam-a-levy.github.io)), the mobile version displays without any of the visuals that it used to (e.g. sidebar, topbar etc.) as shown in the attached picture 
![WhatsApp Image 2023-04-29 at 17 25 24](https://user-images.githubusercontent.com/57630097/235310730-ee68a5fe-517b-4893-ba76-40bab5e77ed2.jpeg)

**Comment by ahmed-elhefnawy** [comment]
I've exactly the same issue but both on the desktop and mobile versions!

**Comment by siddharthksah** [comment]
Hello, I encountered a similar issue, and I was able to resolve it by making adjustments to the _config.yml file:

```diff
- url: https://siddharthksah.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
+ url: https://www.siddharthsah.com # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"

By updating the URL from https://siddharthksah.github.io to https://www.siddharthsah.com, the issue was resolved successfully.

**Comment by dgl2000** [comment]
> Hi, I encountered a similar issue, and I was able to resolve it by making adjustments to the _config.yml file:
> 
> ```diff
> - url: https://siddharthksah.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
> + url: https://www.siddharthsah.com # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
> 
> By updating the "url" from https://siddharthksah.github.io to https://www.siddharthsah.com, the issue was resolved successfully.
> ```

Works for me! Thanks
