### ISSUE TITLE
changing colors, fonts, font sizes

### ISSUE THREAD

**Issue by cseveren** [academicpages/academicpages.github.io#132]
Thanks for this great template! I'm trying to change the default font size and some colors for the website, in particular because I don't always like how the markdown gets rendered (i.e. my research page below feels to busy). I edited what I think should correspond to these variables in /_sass/_variables.scss (like $doc-font-size and $link-color) but this doesn't appear to make any difference to the website's appearance. I'm still getting my head around this way of organizing website design information, so it's very possible I'm possible a lot. Any guidance is appreciated.

https://cseveren.github.io/
https://cseveren.github.io/research

Thanks

**Comment by cseveren** [comment]
After more searching, I have two answers:

1. to change global site setting, not only should you change `$doc-size-font` in `_variables.scss` but also the font size in `_reset.scss`, see: https://github.com/mmistakes/minimal-mistakes/issues/1043

1. to change just the way the markdown shows up on most content pages, change `font-size` variables under `.page__content` in `_pages.scss`. I like 13pt, so 0.875em with 16pt standard. 

Maybe this was obvious if you've worked in this framework for awhile, but it me a lot of searching to figure this out.

**Comment by SibylGao** [comment]
Helps a lot, thanks.

**Comment by thaherxyz** [comment]
Thanks Chris! Roughly 5 years later and this is still helpful
