### ISSUE TITLE
Tikz diagrams

### ISSUE THREAD

**Issue by kartheekmedathati** [academicpages/academicpages.github.io#1344]
Hi! Is there a way to include tikz diagrams in the markdown? 

Thanks for sharing this.

**Comment by rjzupkoii** [comment]
While support for Tikz diagrams would be very powerful, based upon the limitations of GitHub Pages, it doesn't appear that there would be a way of offering native support for them. As it is, Mermaid diagrams (see #2303) are also blocked right now by the limitations of GitHub Pages.
