### ISSUE TITLE
Range of publications in publication page

### ISSUE THREAD

**Issue by jw447** [academicpages/academicpages.github.io#135]
Is there any way to set the section size in _pages/publications.md? I understand that it involves the archive-single.html but i'm having difficulties figuring out how to modify that.

**Comment by rjzupkoii** [comment]
This looks like something that should be addressed at the same time as #48

**Comment by rjzupkoii** [comment]
Looking at this item a second time, what do you mean by the section size? The formatting of the page or the number of items included?

**Comment by rjzupkoii** [comment]
Closing since this issue looks to be stale.
