### ISSUE TITLE
Markdown-style links are not displayed with some color in the webpage.

### ISSUE THREAD

**Issue by Datseris** [academicpages/academicpages.github.io#138]
Let's say that I write in CV some simple markdown link: `[some text](www.google.com)`. When I look at the "rendered" page at github pages, I see that the text `some text` has exactly the same color as all the rest, making it impossible to tell that this text is actually a link.

How do I fix this?

**Comment by jlchan** [comment]
Seconded on this.  I've noticed that it works on the home (about.md) page, but not on other pages.  

Github's markdown seems to have trouble with colors, so I haven't been able to get colored links.  I've just added emphasis `[**some text**]` around the link to at least draw attention to it.

**Comment by jlchan** [comment]
Figured out one way around it.  The links are colored for "layout: single" but not for "layout: archive".  Switching to "layout: single" colors all links.  

Unfortunately, switching to "layout: single" also makes the text margins narrower.  Trying to figure out how to customize the formats in _layouts/ to give wide margins and also colored links.

**Comment by staeiou** [comment]
I've changed some of the CSS to make most links underlined by default, which is in commit 5055f27e5d. I think other variables in `_sass/_page.scss` could be changed around this, but I'm not 100% sure.

**Comment by shivaat** [comment]
I managed to make it work by doing some changes on _sass/_archive.scss. Commit as follows:

https://github.com/shivaat/shivaat.github.io/commit/85a11501b44d5d3bd1769e714d2528562f9f87f1

**Comment by rjzupkoii** [comment]
Closing since this seems to have been addressed at some point already.
