### ISSUE TITLE
Images are not getting displayed

### ISSUE THREAD

**Issue by sriharsha0806** [academicpages/academicpages.github.io#140]
https://sriharsha0806.github.io/posts/2012/08/blog-post-2/

https://github.com/sriharsha0806/sriharsha0806.github.io/blob/master/_posts/2018-07-17-blog-post-2.md

I have posted the blog post link and block post md file for comparision. The Images are displayed in blog post whereas in blog post .md file you can see. May i  know why is it happening?

**Comment by SreenivasVRao** [comment]
It should be possible to get them to work with local images. However, I found a work around after digging around with the author's own blog posts. 

Basically, host the images online on a website like imgur, and link to it.
For example to embed this picture: `![](https://i.imgur.com/bdWWcsf.jpg)`

https://github.com/staeiou/staeiou.github.io/blob/master/_posts/2018-04-16-keeping-computation-interpretation-ethoslab.md

#80

**Comment by sriharsha0806** [comment]
Thanks

**Comment by drdh** [comment]
Hi, I have the same problem, and I find another solution.

The problem is:

```
_posts/abc.md
_posts/abc.jpg
```
I noticed that when I insert images like that, `![](abc.jpg)`, I got an error like that, `RROR  '/posts/abc.jpg' not found.`

It changes `_posts` to `posts`. !

So I create another directory `posts`, and now the files are as follows

```
_posts/abc.md
posts/abc.jpg
```
And insert images `![](abc.jpg)`.
 It works.

**Comment by someshsingh22** [comment]
Ok so the teaser items in the CSS are same, the related story teaser looks appropriate while the blogpost list's teasers are unusually large (on desktop), when I decrease the size say 50% width and height the teaser is too small for related stories.

How can we set different sizes dor both of them, It would be a huge help.

**Comment by Tatianabellagio** [comment]
Thanks so much!! After trying so many things 
```
_posts/abc.md
posts/abc.jpg
```
this worked for me!

**Comment by Zijia-Cheng** [comment]
> Ok so the teaser items in the CSS are same, the related story teaser looks appropriate while the blogpost list's teasers are unusually large (on desktop), when I decrease the size say 50% width and height the teaser is too small for related stories.
> 
> How can we set different sizes dor both of them, It would be a huge help.

Hi, may I ask how to change figure size in markdown files? Thanks!

**Comment by rlucas7** [comment]
https://github.com/academicpages/academicpages.github.io/issues/91#issuecomment-2427689676

^linked comment fixed this issue for me
