### ISSUE TITLE
Is it possible to modify blog preview?

### ISSUE THREAD

**Issue by pswpswpsw** [academicpages/academicpages.github.io#148]
The blog preview now contains duplicated information about the post. Is it possible to keep a clean template for the blog? 

For example, when click into the blog, I would see the post name and the title in that blog, which makes information duplicated.

**Comment by SreenivasVRao** [comment]
There's an excerpts tag. From the authors original repo:

https://github.com/staeiou/staeiou.github.io/blob/master/_posts/2006-05-05-notions-of-identity-liberation-in-virtual-gaming-communities.md
