### ISSUE TITLE
make picture larger

### ISSUE THREAD

**Issue by jafflerbach** [academicpages/academicpages.github.io#15]
How can we easily adjust the size of the profile photo? The default is quite small...

**Comment by staeiou** [comment]
Hi, that is in [_sass/_sidebar.scss](https://github.com/academicpages/academicpages.github.io/blob/master/_sass/_sidebar.scss) and I've increased the default font size in this repo. Replace that file in your repo with the one in this one and it should be a bit bigger. Let me know if it works or not!

**Comment by jafflerbach** [comment]
I upped the max pixels to 200 and am happy with how it looks now, thanks!
