### ISSUE TITLE
How to reduce the margin of pages

### ISSUE THREAD

**Issue by yichx** [academicpages/academicpages.github.io#1515]
I want to narrow the sidebar and reduce the margin of pages. What change can I make?

**Comment by wvirany** [comment]
Hi @yichx,

Can you describe how you achieved this?

Thanks

**Comment by CaucherWang** [comment]
I also want to know how to reduce the right margin. Thx.

**Comment by rjzupkoii** [comment]
@CaucherWang Please see #1996, if all goes well I'll have something written up in the next couple days.
