### ISSUE TITLE
Additional hyperlinks in publications page not highlighted

### ISSUE THREAD

**Issue by michaelfaulkner** [academicpages/academicpages.github.io#157]
After having added "Open-source versions are available on the [arXiv](link) and citation information is available on [Google Scholar](link)." to publications.md, I've found that those additional hyperlinks aren't highlighted (although they do work). Would it be possible to fix this?

P.S. Thanks very much for making this template available. Much appreciated.

**Comment by xingjunm** [comment]
Hi if you use "layout: archive"
Try change line 17-20 in _sass/_archive.scss 
a {
    color: inherit;
    text-decoration: none;
  }
-->
a {
    text-decoration: underline;

    &:hover {
      text-decoration: underline;

      img {
        box-shadow: 0 0 10px rgba(#000, 0.25);
      }
    }
  }

change the corresponding css style in _sass if other layout used.

**Comment by michaelfaulkner** [comment]
Apologies, I forgot to reply this. Was a long time ago but thanks for your help!
