### ISSUE TITLE
Open social links in sidebar in new tab

### ISSUE THREAD

**Issue by AntoineSoetewey** [academicpages/academicpages.github.io#159]
Is it possible to open social links in the sidebar in a new tab, similarly to html links with target=”_blank”?

**Comment by ASeatonSpatial** [comment]
Did you manage to do this?  My twitter and github links only work when opened in a new tab.  Just single clicking them doesn't work

**Comment by AntoineSoetewey** [comment]
Yes. In the file author-profile.html, simply add target="_blank" for the links you want to open in a new tab. Have a look at [my file](https://github.com/AntoineSoetewey/antoinesoetewey.github.io/blob/master/_includes/author-profile.html) if you need help.
