### ISSUE TITLE
jekyll serve locally

### ISSUE THREAD

**Issue by vlamen** [academicpages/academicpages.github.io#16]
I am unable to run the site locally. Jekyll serve requires bundle install. 

bundle install fails on dependencies:

Could not find gem 'jekyll-sitemap (= 0.10.0) x64-mingw32', which is required by gem 'github-pages', in any
of the sources.

**Comment by staeiou** [comment]
I think I've fixed this in 8afd47deb -- it was set up to pull from the jekyll-sitemap GitHub master branch, this should make it pull the release version from rubygems.org. I've also added some steps to serve locally on the readme. If this doesn't work, delete Gemfile.lock and try `bundle install` again.
