### ISSUE TITLE
additional links in sidebar not appearing

### ISSUE THREAD

**Issue by AntoineSoetewey** [academicpages/academicpages.github.io#160]
I tried to add additional links in the sidebar (below the default ones such as github, linkedin, email, ect.) as explained in [https://mmistakes.github.io/minimal-mistakes/docs/configuration/](https://mmistakes.github.io/minimal-mistakes/docs/configuration/). In particular, I'd like to add a link to my researchgate profile (with the researchgate icon) and a link to my contact page (with the envelope icon).

Although I tried many different links, none of the link I added is appearing.

You can see the links I tried [here](https://github.com/AntoineSoetewey/antoinesoetewey.github.io/blob/master/_config.yml).

Thanks in advance for your help.

**Comment by bensdm** [comment]
same issue, did you solve it?

**Comment by AntoineSoetewey** [comment]
Yes, edit your file _includes/author-profile.html. You can check my code [here](https://github.com/AntoineSoetewey/antoinesoetewey.github.io/blob/master/_includes/author-profile.html) to see how I added more links.
