### ISSUE TITLE
Adding telegram icon to config and updating the twitter icon to `X`

### ISSUE THREAD

**Issue by dhancodes** [academicpages/academicpages.github.io#1600]
- [x] Add telegram icon in the sidebar
- [x] Update the current twitter icon to `X`

**Comment by simplyydev** [comment]
Please consider adding a pull request and doing it on the go

**Comment by jacksonchen1998** [comment]
I try to modify the twitter icon like this 

```html
{% if author.twitter %}
        <li><a href="https://twitter.com/{{ author.twitter }}"><i class="fab fa-fw fa-square-x-twitter" aria-hidden="true"></i> Twitter</a></li>
      {% endif %}
```

But it doesn't work. So, I think the origin uses the older version, Fontawesome version 4.

Reference:
[Fontawesome version 5](https://fontawesome.com/search?q=twitter&o=r&f=classic%2Cbrands)

**Comment by kennethbunker** [comment]
Is there any update on this issue? Old twitter icon still showing.

**Comment by rjzupkoii** [comment]
Updated to Font Awesome 6, switched to the X icon, added Telegram and a placeholder for Bluesky (pending #1917)
