### ISSUE TITLE
Lost the theme format for my webpage

### ISSUE THREAD

**Issue by sagihaider** [academicpages/academicpages.github.io#1794]
I am facing difficulties as I seem to have lost the theme format for my webpage https://sagihaider.com/
 It was loading perfectly two months ago, but after adding publications, it is not displaying properly on a desktop/PC. Interestingly, the webpage works perfectly on mobile devices. 
Could you please provide a solution or assistance?
Thank you!

<img width="1433" alt="Screenshot 2024-01-01 at 23 51 03" src="https://github.com/academicpages/academicpages.github.io/assets/17647329/5130a6cb-e2ff-43b4-92a1-f6fc610bfcf2">
I am attaching a screenshot for the reference.

**Comment by penguinaugustus** [comment]
I meet the same problem...

**Comment by nOw-Ay** [comment]
@sagihaider @penguinaugustus, you should try to uncheck "Enforce HTTPS", it worked for me.
Another option is replacing all the http occurrences by https ones.

**Comment by sagihaider** [comment]
Just tried enforcing HTTPS and no effect.

**Comment by nOw-Ay** [comment]
> Just tried enforcing HTTPS and no effect.

Well I did the opposite and it worked. But I think your problem is about SSL : if I consult your website using http, everything works well.

**Comment by sagihaider** [comment]
Are you using desktop/pc? Because on mobile browser it is working well. However, when loading from PC issue remains the same.

**Comment by penguinaugustus** [comment]
I thinks the problem is even i uncheck `enforcing HTTPS`, sometimes my browser would automatically add `https`. I can fix it by changing the prefix to `http` but is there anyway to automatically enforce HTTP?

**Comment by jwangjie** [comment]
> Are you using desktop/pc? Because on mobile browser it is working well. However, when loading from PC issue remains the same.

@sagihaider I wonder if you can share the method you used to solve this issue? Thanks.

**Comment by sagihaider** [comment]
Hi, I am using MAC so I did a hard refresh and it worked (⌘ Cmd and ⇧ Shift key and then press R).

**Comment by rjzupkoii** [comment]
It sounds like this issue is resolved, correct?

**Comment by sagihaider** [comment]
Yes, I think so. We can close the issue. 
Thank you!

**Comment by jwangjie** [comment]
I haven't been able to resolve the issue on my end. It's interesting to know that a `hard refresh` solves it, given that the problem stems from the browser automatically adding https. I would greatly appreciate any additional suggestions. Thank you.

**Comment by rjzupkoii** [comment]
@jwangjie When I've been doing development I need to do a hard refresh as well, plus sometimes restarting Jekyll depending upon what I'm working on. However, you may have some libraries out of date so you may want to try running `bundle update` and see if that helps. You may also want to open up a [new topic in the discussion](https://github.com/academicpages/academicpages.github.io/discussions) since closed issues don't get much attention.
