### ISSUE TITLE
pages build and deployment - New Jekyll Update

### ISSUE THREAD

**Issue by wvirany** [academicpages/academicpages.github.io#1878]
Hello,

It seems that an issue has developed with the Jekyll dependencies. After having made a minor change that should not have thrown an error, I am now unable to pass the `pages build and deployment` step. Here is the warning I am getting:

`Warning: The github-pages gem can't satisfy your Gemfile's dependencies. If you want to use a different Jekyll version or need additional dependencies, consider building Jekyll site with GitHub Actions: https://jekyllrb.com/docs/continuous-integration/github-actions/`

which turns into this error:

`Error:  Logging at level: debug Configuration file: /github/workspace/./_config.yml GitHub Pages: github-pages v229 GitHub Pages: jekyll v3.9.4 Theme: jekyll-theme-primer Theme source: /usr/local/bundle/gems/jekyll-theme-primer-0.6.0 Requiring: jekyll-github-metadata Requiring: jekyll-seo-tag Requiring: jekyll-paginate Requiring: jekyll-sitemap Requiring: jekyll-gist Requiring: jekyll-feed Requiring: jekyll-redirect-from Requiring: jekyll-coffeescript Requiring: jekyll-commonmark-ghpages Requiring: jekyll-github-metadata Requiring: jekyll-relative-links Requiring: jekyll-optional-front-matter Requiring: jekyll-readme-index Requiring: jekyll-default-layout Requiring: jekyll-titles-from-headings GitHub Metadata: Initializing... Source: /github/workspace/. Destination: /github/workspace/./_site Incremental build: disabled. Enable with --incremental Generating... EntryFilter: excluded /package.json EntryFilter: excluded /CHANGELOG.md EntryFilter: excluded /LICENSE EntryFilter: excluded /Gemfile EntryFilter: excluded /README.md Reading: _posts/2013-08-14-blog-post-2.md Reading: _posts/2012-08-14-blog-post-1.md Reading: _posts/2015-08-14-blog-post-4.md Reading: _posts/2199-01-01-future-post.md Reading: _posts/2014-08-14-blog-post-3.md Skipping: _posts/2199-01-01-future-post.md has a future date EntryFilter: excluded /assets/js/plugins EntryFilter: excluded /assets/js/vendor Reading: _teaching/2014-spring-teaching-1.md Reading: _teaching/2015-spring-teaching-2.md Reading: _publications/2015-10-01-paper-title-number-3.md Reading: _publications/2010-10-01-paper-title-number-2.md Reading: _publications/2009-10-01-paper-title-number-1.md Reading: _portfolio/portfolio-3.html Reading: _portfolio/portfolio-4.html Reading: _portfolio/portfolio-2.html Reading: _portfolio/portfolio-1.md Reading: _talks/building_neural_net.md Generating: JekyllRedirectFrom::Generator finished in 0.025129754 seconds. Generating: JekyllOptionalFrontMatter::Generator finished in 0.000362375 seconds. Generating: JekyllReadmeIndex::Generator finished in 0.000577715 seconds. Generating: Jekyll::Paginate::Pagination finished in 5.621e-06 seconds. Generating: Jekyll::JekyllSitemap finished in 0.000335906 seconds. Jekyll Feed: Generating feed for posts Generating: JekyllFeed::Generator finished in 0.000673564 seconds. github-pages 229 | Error: undefined method 'excerpt_separator' for #<Jekyll::Page @name="404.md"> `

Supposedly the `excerpt_separator` method is undefined. This seems to be a backend problem that I do not understand. Thanks for the help!

**Comment by wvirany** [comment]
Note: I even reverted to a previous commit which originally deployed successfully. Now, that commit throws this error.

**Comment by 2prime** [comment]
I think the reason is github updated jekyll to v3.9.4. But I don't know how can I rollback

**Comment by dariusdotdk** [comment]
Same problem

**Comment by WilderLavington** [comment]
Me as well.

**Comment by marksherriff** [comment]
There's further discussion in Jekyll's repo (https://github.com/jekyll/jekyll/issues/9544) with suggestions of using GitHub Actions to setup your own deploy action where you can force the rollback to 3.9.3 or to build locally on 3.9.3 and push to the _site directory.  I'm not sure how viable either of these alternatives are, considering it's much more convenient to rely on the github-pages package to manage this.

**Comment by marksherriff** [comment]
Well, a very silly solution is to remove all the excerpt tags from the frontmatter of all the pages.  I removed the excerpt from the 404.md page and Jekyll got past it... and then failed on about.md.  Unfortunately, excerpts are leaned on pretty heavily in this theme, so I doubt this is a great option.  But perhaps if someone has only a page or two, this would suffice for them in the interim.

**Comment by amitabhadey** [comment]
Was anyone able to resolve the issue? I have already tried all sorts of things but to no avail. 

1. Initially, I thought my recent push corrupted some core files, so I did a quick git checkout to a previous successful commit. That didn't work. 
2. I tried to roll back to Jekyll 3.9.3 by first doing a clean uninstall of my current Jekyll, then removed Gemfile.lock, did a fresh installation of 3.9.3, updated gem bundler and finally performed bundle install. I was able to roll back but the deployment still didn't work for me. It did for some people, as mentioned [here](https://talk.jekyllrb.com/t/local-windows-dev-environment-for-github-pages-theme/8938/4) and [here](https://github.com/jekyll/jekyll/issues/9544).
3. The warning points you to this [link](https://jekyllrb.com/docs/continuous-integration/github-actions/). Tried to follow the instructions but that didn't work either.

**Comment by vince-lam** [comment]
I have the same issue, will try the solution of creating a jekyll-github-pages.yml in the discussion shared by @marksherriff later

**Comment by WillJardee** [comment]
> Well, a very silly solution is to remove all the excerpt tags from the frontmatter of all the pages. I removed the excerpt from the 404.md page and Jekyll got past it... and then failed on about.md. Unfortunately, excerpts are leaned on pretty heavily in this theme, so I doubt this is a great option. But perhaps if someone has only a page or two, this would suffice for them in the interim.

Turns out you only have to delete the line from three files (404, about, and non-menu-page). I am not sure what the long-term ramifications are, but after cleaning those three the website deployed.

**Comment by amitabhadey** [comment]
> > Well, a very silly solution is to remove all the excerpt tags from the frontmatter of all the pages. I removed the excerpt from the 404.md page and Jekyll got past it... and then failed on about.md. Unfortunately, excerpts are leaned on pretty heavily in this theme, so I doubt this is a great option. But perhaps if someone has only a page or two, this would suffice for them in the interim.
> 
> Turns out you only have to delete the line from three files (404, about, and non-menu-page). I am not sure what the long-term ramifications are, but after cleaning those three the website deployed.

This worked for me! Thank you so much!

**Comment by marksherriff** [comment]
> > Well, a very silly solution is to remove all the excerpt tags from the frontmatter of all the pages. I removed the excerpt from the 404.md page and Jekyll got past it... and then failed on about.md. Unfortunately, excerpts are leaned on pretty heavily in this theme, so I doubt this is a great option. But perhaps if someone has only a page or two, this would suffice for them in the interim.
> 
> Turns out you only have to delete the line from three files (404, about, and non-menu-page). I am not sure what the long-term ramifications are, but after cleaning those three the website deployed.

Do you have excerpts on other pages, such as your own content?  I have excerpts on all my research project pages which generates a project listing page.

**Comment by jchackett-lcsw** [comment]
Installing this for the first time and these workaround were really helpful. I second that you only need to edit the 3 files from @WillJardee.

**Comment by wvirany** [comment]
> > > Well, a very silly solution is to remove all the excerpt tags from the frontmatter of all the pages. I removed the excerpt from the 404.md page and Jekyll got past it... and then failed on about.md. Unfortunately, excerpts are leaned on pretty heavily in this theme, so I doubt this is a great option. But perhaps if someone has only a page or two, this would suffice for them in the interim.
> > 
> > 
> > Turns out you only have to delete the line from three files (404, about, and non-menu-page). I am not sure what the long-term ramifications are, but after cleaning those three the website deployed.
> 
> Do you have excerpts on other pages, such as your own content? I have excerpts on all my research project pages which generates a project listing page.
> 
> EDIT: I removed the excerpt from just the 404, about, and non-menu-page as suggested and even though I have excerpts on many other pages, the site built properly on github pages. So, victory for all! :-)

@marksherriff I did the same and now my site deploys without any problems. Thanks for the help!

**Comment by wvirany** [comment]
> > Well, a very silly solution is to remove all the excerpt tags from the frontmatter of all the pages. I removed the excerpt from the 404.md page and Jekyll got past it... and then failed on about.md. Unfortunately, excerpts are leaned on pretty heavily in this theme, so I doubt this is a great option. But perhaps if someone has only a page or two, this would suffice for them in the interim.
> 
> Turns out you only have to delete the line from three files (404, about, and non-menu-page). I am not sure what the long-term ramifications are, but after cleaning those three the website deployed.

@WillJardee I did this and the site deploys without any problems. Thanks!
