### ISSUE TITLE
The site is not updating!

### ISSUE THREAD

**Issue by vardanbarsegyan** [academicpages/academicpages.github.io#1887]
Hi everyone, 

since yesterday, the site does not save any commits on the web page (https://www.vardanbarsegyan.com). Regardless what page I update, I get the same error: "pages build and deployment / build Failed in 19 seconds". 
What should I do?

Best,
Vardan

**Comment by geraldsimanullang** [comment]
I found the solution on [StackOverflow](https://stackoverflow.com/questions/77972098/github-jekyll-page-build-keeps-failing). Removing the **'excerpt=...'** line from these files solved the problem for me:
* _pages/404.md
* _pages/about.md 
* _pages/non-menu-page.md

**Comment by femi-jinadu** [comment]
@vardanbarsegyan did you find a fix? facing the same challenge, removing the 'excerpts=...'  line in these files did not fix it.

**Comment by vardanbarsegyan** [comment]
@geraldsimanullang @femi-jinadu  thanks for the advice, however, removing the lines with "excerpts" did not fix the problem. Moreover, I don't have "excerpts = ". I have only "excerpts : ".

**Comment by rllob** [comment]
> I found the solution on [StackOverflow](https://stackoverflow.com/questions/77972098/github-jekyll-page-build-keeps-failing). Removing the **'excerpt=...'** line from these files solved the problem for me:
> 
> * _pages/404.md
> * _pages/about.md
> * _pages/non-menu-page.md

I tried this, and it worked for me. Thank you!

**Comment by vardanbarsegyan** [comment]
Hi everyone, the issue is resolved by deleting the "excerpt" line from ALL individual pages! 
Thank you!

**Comment by chujiezheng** [comment]
> I found the solution on [StackOverflow](https://stackoverflow.com/questions/77972098/github-jekyll-page-build-keeps-failing). Removing the **'excerpt=...'** line from these files solved the problem for me:
> 
> * _pages/404.md
> * _pages/about.md
> * _pages/non-menu-page.md

This works for me. Thank you!
