### ISSUE TITLE
Author profile sidebar jitters with hover

### ISSUE THREAD

**Issue by a-paxton** [academicpages/academicpages.github.io#19]
When hovering over the author sidebar profile, the opacity transition seems to cause it to jitter.

**Comment by staeiou** [comment]
Good eye! Now fixed in f75727466a91847b2268a7736c14d09d9efc8652, which is a small patch to _sass/sidebar.scss from mmistakes (https://github.com/mmistakes/minimal-mistakes/issues/583). Reminds me that I need to do a refactor/patch upstream from mmistakes...
