### ISSUE TITLE
Have 'Page not found' trouble with publications.

### ISSUE THREAD

**Issue by Ericonaldo** [academicpages/academicpages.github.io#193]
I set "publications.md" in "/_pages" as [this](https://github.com/goatman1/goatman1.github.io/blob/master/_pages/publications.md).

And I set "HTRDJournal.md" in "_pulications" as [this](https://github.com/goatman1/goatman1.github.io/blob/master/_pulications/HTRDJournal.md).

The page of "goatman1.github.io/publications" works well, but when I click the link of the title which is "goatman1.github.io/publications/HTRDJournal", it always warns that "Page not found". There are no grammar error in both file. For a long time I can not figure out why. Can you tell me what did I miss?

**Comment by doylethomas** [comment]
Looks like a spelling mistake "_pulications/HTRDJournal.md"  

Should be "_publications/HTRDJournal.md", no?

**Comment by Ericonaldo** [comment]
> Looks like a spelling mistake "_pulications/HTRDJournal.md"
> 
> Should be "_publications/HTRDJournal.md", no?

Damn it... u r so right... thanks very much!!! And how silly I am... Orz
But still some problem with /projects, maybe some other stupid mistakes...
