### ISSUE TITLE
How to remove FOLLOW:GITHUB FEED in the footer

### ISSUE THREAD

**Issue by ChengruiHan** [academicpages/academicpages.github.io#1935]
I don't like FOLLOW:GITHUB FEED in the footer and i want to remove them. However, i don't know how to deal with it. Could someone help me and give some necessary details? Thank you so much.
<img width="655" alt="截屏2024-02-23 10 56 10" src="https://github.com/academicpages/academicpages.github.io/assets/140309590/baed7aa3-e0e4-4dc1-b422-8c6210ce78f9">

**Comment by rjzupkoii** [comment]
There are two sources for these:
1. The "Follow" text and the social media icons (i.e., "GitHub" in the above example, are produced when a relevant social media username is supplied in `_config.yml`. So in your case, removing "academicpages" as the username in your configuration should disable that showing.
2. The second item, "Feed" is an RSS feed that allows people to subscribe to updates on your site. At this time there's not an easy way of disabling that without editing the code. I've created issue #1936 to address that and should have the code updated in the next couple days.

**Comment by rjzupkoii** [comment]
If RSS is disabled and the user does not have a GitHub or Bitbucket account, the "Follow" line in the footer is automatically removed by the template.

**Comment by ChengruiHan** [comment]
Thanks a lot !

**Comment by ChengruiHan** [comment]
> 这些有两个来源：
> 
> 1. “关注”文本和社交媒体图标（即上例中的“GitHub”）是在 中提供相关社交媒体用户名时生成的`_config.yml`。因此，在您的情况下，删除配置中的用户名“academicpages”应禁用那个表现。
> 2. 第二项“Feed”是 RSS 提要，允许人们订阅您网站上的更新。目前，没有一种简单的方法可以在不编辑代码的情况下禁用它。我已经创建了问题[允许用户在页脚中禁用 RSS feed ](https://github.com/academicpages/academicpages.github.io/issues/1936)[ #1936](https://github.com/academicpages/academicpages.github.io/issues/1936)来解决这个问题，并且应该在接下来的几天内更新代码。[](https://github.com/academicpages/academicpages.github.io/issues/1936)


Thanks a lot !

**Comment by ChengruiHan** [comment]
> There are two sources for these:
> 
> 1. The "Follow" text and the social media icons (i.e., "GitHub" in the above example, are produced when a relevant social media username is supplied in `_config.yml`. So in your case, removing "academicpages" as the username in your configuration should disable that showing.
> 2. The second item, "Feed" is an RSS feed that allows people to subscribe to updates on your site. At this time there's not an easy way of disabling that without editing the code. I've created issue [Allow users to disable RSS feed in the footer #1936](https://github.com/academicpages/academicpages.github.io/issues/1936) to address that and should have the code updated in the next couple days.

Thanks a lot !
