### ISSUE TITLE
Font Change

### ISSUE THREAD

**Issue by mohsin651** [academicpages/academicpages.github.io#1959]
How can I globally change the font on a website, including the footer, navbar, and sidebar?

**Comment by rjzupkoii** [comment]
The master location for fonts is in `_sass/_variables` and the lines that govern the fonts look like this:

```sass
$global-font-family         : $sans-serif;
$header-font-family         : $sans-serif;
$caption-font-family        : $serif;
```

By default the `$sans-serif` variable is used which uses the following default and fail overs:

```sass
$sans-serif                 : -apple-system, ".SFNSText-Regular", "San Francisco", "Roboto", "Segoe UI", "Helvetica Neue", "Lucida Grande", Arial, sans-serif;
```

If you are going to change the template font is recommended that you define a new font variable that includes fail overs like the `$sans-serif` variable and then assign that variable to the primary variables listed above.

**Comment by mohsin651** [comment]
How to use external font,  I installed "Lucida Sans" on my system, and replace in the place of "-apple-system", it worked locally, but not on deployment, why so?
