### ISSUE TITLE
Markdown footnotes are not rendered correctly

### ISSUE THREAD

**Issue by rjzupkoii** [academicpages/academicpages.github.io#1972]
### Discussed in https://github.com/academicpages/academicpages.github.io/discussions/1969

<div type='discussions-op-text'>

<sup>Originally posted by **muddin21** March  5, 2024</sup>
# Footnotes and alerts not working properly
Hi All,
I appreciate your assistance with following issue:
https://github.com/academicpages/academicpages.github.io/pull/1962#issue-2167450219</div>

**Comment by muddin21** [comment]
Footnotes are now working by changing `markdown: kramdown` to `markdown: GFM`, but alerts are not working properly yet.

**Comment by rjzupkoii** [comment]
The [documentation](https://academicpages.github.io/markdown/) has been updated to better explain how footnotes and notices work. The syntax for notices is not standard markdown and would require a bit of additional formatting to look the same as GitHub.
