### ISSUE TITLE
Social share buttons missing logo

### ISSUE THREAD

**Issue by falcon97** [academicpages/academicpages.github.io#199]
The logo in the share buttons for Twitter, Facebook , Google+ and LinkedIn is absent. I can only see a square box instead of the respective logos. Request you to fix this.

![image](https://user-images.githubusercontent.com/26250467/52527198-b250d500-2c92-11e9-9895-f4cfc7e0d1a5.png)

Apart from that, it's an amazing template. Thank you!

**Comment by Yunaik** [comment]
You can change the `fa` in `fa fa-fw fa-facebook` to `fab fa-fw fa-facebook`. Also, you probably want to rename the icons. See changes from fontawesome 4 to 5: https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

**Comment by falcon97** [comment]
Thank you Yunaik. This fixed the issue!
