### ISSUE TITLE
Support bibtex or other standardized citations for publications

### ISSUE THREAD

**Issue by staeiou** [academicpages/academicpages.github.io#2]
Right now, citations have to be manually formatted.

**Comment by staeiou** [comment]
Bibtex is probably the way to go on this, all the major platforms and citation management tools I know of have an export to Bibtex (Zotero, Mendeley, ORCID).

**Comment by johnsonlab** [comment]
Also would be excited to see bibtex support added. If the choice between citation keys for 

LaTeX:  ~\cite{pmid26965313,}

versus

RMarkdown / Rstudio: [@pmid26965313]

is available, the latter is a good deal more convenient/fewer chars.

**Comment by rjzupkoii** [comment]
Closing in favor of tracking using #1093
