### ISSUE TITLE
How to make posts in the added collection visible in category tab?

### ISSUE THREAD

**Issue by arcstone09** [academicpages/academicpages.github.io#2007]
I want to make my posts displayed by its category when ‘category’ tab is clicked.

In order to do this, I uncommented the ‘jekyll-archives’ part in _config.yml.

For posts in collections which are already in the template(ex.  Blog posts), it works.

However, posts that are located in collection that I added don’t appear when I click the category tab. What should I do?

(To add collection, I changed _config.yml collections part and navigation.yml file, added [collection_name].html file in _pages folder, and wrote new posts with category in the folder named _study that I made. Posts in _study folder is visible in the ‘study’ tab, but not visible in the ‘category’ tab.)

**Comment by rjzupkoii** [comment]
Do you mean that you want posts sorted by category - as opposed to date - when something is clicked, or are creating a new category that appears in the menu?

**Comment by arcstone09** [comment]
I want posts sorted by category. (I guess /_pages/category-archive.html does this)

I wrote new posts as below, and it appears in the 'study' menu, but not in 'Category' menu(which links to category-archive.html) 
---
title: 'test'
date: 2024-03-18
permalink: /study/2024-03-18-study-1
categories: coding
tags:
  - cool posts
  - category1
  - category2
---

This post will show up by default. To disable scheduling of future posts, edit `config.yml` and set `future: false`. 

However, for posts not in study menu, they are visible when I click 'Category' menu and sorted by their categories.

**Comment by arcstone09** [comment]
> Do you mean that you want posts sorted by category - as opposed to date - when something is clicked, or are creating a new category that appears in the menu?

If you visit arcstone09.github.io site and go to 'Category' menu, posts with categories name 'coding' would be displayed. A post titled 'test' which is visible in Study menu is also classified as 'coding' category, but it is not shown in the 'Category' menu. Thanks a lot.
