### ISSUE TITLE
Adding social media links

### ISSUE THREAD

**Issue by anjalibhavan** [academicpages/academicpages.github.io#201]
Hi,
I wished to add links to other social media handles like Quora and WordPress (with icons). Where do I add the code for it, and how do I do that?

**Comment by anjalibhavan** [comment]
I solved it, apologies. In case anyone is wondering, you simply have to add the line for the concerned URL in author-profile.html and _config.yml. Add the required class like given for the other social media handles; you can see the class names on https://fontawesome.com/icons/.

**Comment by rodrigovimieiro** [comment]
You can find [here](https://jpswalsh.github.io/academicons/) some academic icons.
