### ISSUE TITLE
Navigation bar overlapping with masthead line

### ISSUE THREAD

**Issue by boyuanzhang62** [academicpages/academicpages.github.io#2055]
Hello, thanks for such a wonderful web page template. I run into a problem with the navidation bar as shown in my attached image. The line in the masthead seems like overlapping with the navigation bar, I've checked some youtube videos and theirs seem normal. I tried different browsers it still doesn't work (chrome, safari, edge). Is there any way to fix this?
![image](https://github.com/academicpages/academicpages.github.io/assets/24749533/ca07c3a6-1365-4fa8-892c-401c02cfc9f7)

**Comment by rjzupkoii** [comment]
Most of the YouTube videos are a bit out of date now, but it looks like the template needs to be adjusted down a bit (or I might remove the line since 1px doesn't show very well in general).
