### ISSUE TITLE
Unable to run locally due to dependency issues

### ISSUE THREAD

**Issue by linncy** [academicpages/academicpages.github.io#2061]
**Describe the bug**
I was trying to run locally using the commands specified in README.md
```
sudo apt install ruby-dev ruby-bundler nodejs
bundle install
jekyll serve -l -H localhost
```

However, the bundle command always throws an error:
```
An error occurred while installing bigdecimal (3.1.7), and Bundler cannot continue.

In Gemfile:
  github-pages was resolved to 231, which depends on
    jekyll-mentions was resolved to 1.6.0, which depends on
      html-pipeline was resolved to 2.14.3, which depends on
        activesupport was resolved to 7.1.3.2, which depends on
          bigdecimal
Script execution completed
```

**To Reproduce**
1. Run `sudo apt install ruby-dev ruby-bundler nodejs`
2. Run `bundle install`
3. See error

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 22.04.4 LTS (fresh install)

**Comment by linncy** [comment]
Installing other dependencies solved the issue

```
sudo apt install build-essentials gcc make
```

**Comment by rjzupkoii** [comment]
@linncy Thanks for catching this! I've updated the README with a note on the dependencies.

**Comment by shivamtawari** [comment]
Just a small note: the correct package name is `build-essential` (singular), not `build-essentials` (plural).  The command `sudo apt install build-essential gcc make` should work.
