### ISSUE TITLE
Remove "Published in" in both Teaching and Publication section

### ISSUE THREAD

**Issue by haoliuhoward** [academicpages/academicpages.github.io#21]
Thank you very much for developing this website template. It is really useful and in good-to-go format. A thing I couldn't figure out is how to remove "Published in" this line in both Teaching and Publication sections. It appears to be generated by ```venue:``` in the md files. Commenting them out doesn't help and will still generate a new "Published" logo in the webpage. Could you advise how to resolve this issue? Having "Published in" in Teaching section seems a bit weird.

Thanks a lot!

**Comment by staeiou** [comment]
Good catch, thanks! Should be fixed now in PRs #22 #23 #24 #25 -- ended up messing more things up, then fixed a bug with other types of collections too. [This diff](https://github.com/academicpages/academicpages.github.io/compare/de3dc3c6cdb0f62242fabbd7efc87baaced73bd7...c685f7802c424fdbca7f8b761c4419096f2b9114) shows what you need to change to fix it on your repository.

**Comment by haoliuhoward** [comment]
Thank you. This is really an awesome template.

**Comment by vcangadi1** [comment]
This problem still exists with `venue:` and still produces blank `Published in, 1900` by ommitting one of the references. 

Thanks.

**Comment by BigBluBruin** [comment]
I just want to mention that the problem still exists.

**Comment by FrancescoAlosa** [comment]
> I just want to mention that the problem still exists.

Hi, I have solved the issue for the publication section by leaving row 44 from [_includes/archive-single.html] blank (see solution proposed by @staeiou), and keeping only  <p> <p/> 
Hope this helps!
