### ISSUE TITLE
Date range for Teaching Page

### ISSUE THREAD

**Issue by liamtomosedwards** [academicpages/academicpages.github.io#2108]
Is it possible to provide a date range for the teaching page? For example, if I want to say that I taught a course from 2020-09-25 to 2024-05-01 how would I write this in the Date section of the teaching .md file?

**Comment by rjzupkoii** [comment]
The `date` field of the Markdown file determines the order chronologically, so a range really isn't possible in that field. Right now this is by design, but is there a reason why it would make more sense to have a range in the `date` field as opposed to elsewhere in the teaching page?

**Comment by liamtomosedwards** [comment]
Thank you for explaining it to me. It probably doesn't make sense to have a range in the `date` field, I just wanted to check if there was a workaround. Thank you :)
