### ISSUE TITLE
Footer covers the left sidebar while scrolling the webpage to the bottom.

### ISSUE THREAD

**Issue by fwxie1** [academicpages/academicpages.github.io#2117]
Footer covers the left sidebar while scrolling the webpage to the bottom.
This will cover the content in the left sidebar, which is not pleasing. And even worse, this issue makes the content in left sidebar never fully visible if there is not much, or no, content in the right main area (no need to scroll). 

The sample page (https://academicpages.github.io/) is also like this.

![image](https://github.com/academicpages/academicpages.github.io/assets/148528776/ba961c07-ce66-458e-9cdf-a0f4592c8431)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome version 124

**Comment by rjzupkoii** [comment]
What is the screen resolution when you get this behavior?

**Comment by rjzupkoii** [comment]
Yes, with a 1920x1080 screen the homepage should look like the following in Chrome:

![Untitled](https://github.com/academicpages/academicpages.github.io/assets/1213367/2410b1c7-d5eb-4a88-81ac-2eb1e63778fb)

However, it does seem like your text is a bit larger than the default. Do you have the zoom level increased in Chrome?

**Comment by rjzupkoii** [comment]
It still looks looks like some sort of font scaling is taking place - you might want to check your Windows Display Settings to see what the "Change the size of text, apps, and other items" is set to.
