### ISSUE TITLE
How do I remove a specific section from home menu?

### ISSUE THREAD

**Issue by NhanTran96** [academicpages/academicpages.github.io#216]
I want to remove the **Talks** section from home menu. How can I do it?
Thanks!

**Comment by yabsi** [comment]
if you go to the _config.yml, you should see this section: 

```
talks:
    output: true
    permalink: /:collection/:path/
```

change output to false, and that should do what you want

**Comment by NhanTran96** [comment]
Does anyone know how to do it? 
Thank you in advance.

**Comment by ningyuansg** [comment]
Referring to [this set of diffs](http://archive.is/3TPas) referenced by the README, you should remove the lines referencing "Talks" from [`_data/navigation.yml`](https://github.com/academicpages/academicpages.github.io/blob/master/_data/navigation.yml)

https://github.com/academicpages/academicpages.github.io/blob/06c8b229e323e7cf6e0b32e39aff7871e2d6e707/_data/navigation.yml#L1-L10

**Comment by NhanTran96** [comment]
> Referring to [this set of diffs](http://archive.is/3TPas) referenced by the README, you should remove the lines referencing "Talks" from [`_data/navigation.yml`](https://github.com/academicpages/academicpages.github.io/blob/master/_data/navigation.yml)
> 
> [academicpages.github.io/_data/navigation.yml](https://github.com/academicpages/academicpages.github.io/blob/06c8b229e323e7cf6e0b32e39aff7871e2d6e707/_data/navigation.yml#L1-L10)
> 
> Lines 1 to 10 in [06c8b22](/academicpages/academicpages.github.io/commit/06c8b229e323e7cf6e0b32e39aff7871e2d6e707)
>  # main links links 
>  main: 
>    - title: "Publications" 
>      url: /publications/ 
>   
>    - title: "Talks" 
>      url: /talks/     
>   
>    - title: "Teaching" 
>      url: /teaching/

It works like a a charm. Thank you very much.

**Comment by ningyuansg** [comment]
Glad to have helped. If there’s nothing else, you should close this issue.
