### ISSUE TITLE
pubmed academicon missing

### ISSUE THREAD

**Issue by alcantarar** [academicpages/academicpages.github.io#217]
Pubmed link is present and active on author profile, but academicon is missing:
![Screen Shot 2019-04-12 at 10 46 10 PM](https://user-images.githubusercontent.com/38192529/56074751-cd17f680-5d74-11e9-84b8-5ae133b59804.png)

Repo [here](https://github.com/alcantarar/alcantarar.github.io)

* I checked on `author-profile.html ` and `ai ai-pubmed-square ai-fw` was still there, but not working. 
* I thought it was my adblocker, but icon still doesn't appear with it disabled. 
* Then I updated the academicon css and font files to the academicon v1.8.6 files but it didn't fix it. 
* Thought maybe it was just the pubmed icon. Added fake orcid url to `_config.yml` and  working link pops up, but no icon. 

I can't figure out why academicons are being hidden.

**Comment by yabsi** [comment]
In your: 

https://github.com/alcantarar/alcantarar.github.io/blob/master/_includes/head/custom.html 

You have the css commented: 
 

Uncommenting it seems to do the trick: 

<img width="131" alt="Screen Shot 2019-04-20 at 9 19 42 PM" src="https://user-images.githubusercontent.com/39275070/56464560-0c1bfc80-63b2-11e9-9842-5f3b2e2207b6.png">

**Comment by alcantarar** [comment]
This fixed it. Must have commented it out when I was inserting favicon lines. Thank you!
