### ISSUE TITLE
Jekyll Conversion Error Building Locally

### ISSUE THREAD

**Issue by GBruening** [academicpages/academicpages.github.io#225]
I'm trying to run github pages locally for testing, I followed the steps [here](https://help.github.com/en/articles/setting-up-your-github-pages-site-locally-with-jekyll). 

I'm working off of [academic pages](https://github.com/academicpages/academicpages.github.io).

My repo is [here](https://github.com/GBruening/GBruening.github.io).

### Environment
* __OS__:  windows 10
* __Ruby Version__:      ruby 2.5.5p157 (2019-03-15 revision 67260) [x64-mingw32]
* __Bundler Version__: Bundler version 2.0.1
* __Jekyll Version__:     jekyll 3.8.5

___

When I try to build the site using:
`bundle exec jekyll serve
`

I get the error:
```
Configuration file: E:/Google DRive/github/gbruening.github.io/_config.yml
            Source: E:/Google DRive/github/gbruening.github.io
       Destination: E:/Google DRive/github/gbruening.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
                    File to import not found or unreadable: vendor/breakpoint/breakpoint. Load path: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-theme-primer-0.5.3/_sass on line 10
jekyll 3.8.5 | Error:  File to import not found or unreadable: vendor/breakpoint/breakpoint.
Load path: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-theme-primer-0.5.3/_sass on line 10

```

**Comment by philastrophist** [comment]
I can run your site fine. However, it does report the following errors:

``` 
$ bundle exec jekyll serve
Configuration file: /home/sread/GBruening.github.io/_config.yml
Invalid theme folder: _includes
Invalid theme folder: _includes
            Source: /home/sread/GBruening.github.io
       Destination: /home/sread/GBruening.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
Invalid theme folder: _sass
      Remote Theme: Using theme mmistakes/minimal-mistakes
       Jekyll Feed: Generating feed for posts
                    done in 9.1 seconds.
                    Auto-regeneration may not work on some Windows versions.
                    Please see: https://github.com/Microsoft/BashOnWindows/issues/216
                    If it does not work, please upgrade Bash on Windows or run Jekyll with --no-watch.
 Auto-regeneration: enabled for '/home/sread/GBruening.github.io'
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
[2019-05-13 10:38:27] ERROR `/favicon.ico' not found.
```

Maybe its a windows thing? I'm running this and my own minimalmistakes site in Bash on windows (Ubuntu dist) and it works perfectly. Could you try that?

**Comment by GBruening** [comment]
I realize now that I just switched to minimal mistakes and edited that one, works using that. Thanks for the response!

**Comment by ian-bertolacci** [comment]
@GBruening can you elaborate on how you fixed this?
Did you completely switch to minimal mistakes?
Or did you incorporate changes from current minimal mistakes into your fork of academic pages?
