### ISSUE TITLE
Markdown not rendering syntax highlighting properly

### ISSUE THREAD

**Issue by philastrophist** [academicpages/academicpages.github.io#228]
with the markdown in the _config.yml file as:
```
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class   : 'syntax'
```
and the a post markdown file reading as:
```
(3 backticks) python
import pymc3 
(3 backticks)
 ```

and the css file generated by `rougify style github > assets/css/syntax.css`
I get this:

![image](https://user-images.githubusercontent.com/14169057/57585995-e4b6dc00-74e6-11e9-8d32-7b9dc19eeed0.png)

There are no errors but the style is weird and there is a box in the top corner. How do I get it properly formatted like this guy: https://sacha.me/articles/jekyll-rouge?

**Comment by rjzupkoii** [comment]
The latest updates have helped to improve the syntax highlighting, but something like the referenced website would require a lot more work. If there is interest we could update things with a feature request, but presently it appears that the bug has been addressed and the remainder is by design.
