### ISSUE TITLE
Inconsistent Markdown rendering behavior between template and GitHub

### ISSUE THREAD

**Issue by rjzupkoii** [academicpages/academicpages.github.io#2287]
Users are reporting that GitHub renders Markdown differently than the template once deployed. This should be investigated and either fully documented as to the differences, or the rendering engine updated to align with the one used by GitHub (which may also address #534).

**Comment by rlucas7** [comment]
https://github.com/academicpages/academicpages.github.io/issues/91#issuecomment-2427689676 this fixed the issue for me
