### ISSUE TITLE
Year archive showing the whole blog post

### ISSUE THREAD

**Issue by philastrophist** [academicpages/academicpages.github.io#229]
I originally remove blog posts from my site and deleted the _posts folder a while ago but now I'm putting it back. 
However, the whole blog post appears in the year-archive list instead of just the first bit.

For example in your https://academicpages.github.io/year-archive/, Blog post 3 has headings in its md file but they don't show here. 
In my testing branch https://github.com/philastrophist/philastrophist.github.io.source/tree/bad-posts, it always shows the whole post!

Can someone point out what I've done wrong or tell me how the post is supposed to be trimmed? I don't understand how it works.

**Comment by kennethbunker** [comment]
Did you find out?

**Comment by zhaobingshuai** [comment]
I meet the same error.

**Comment by ikespand** [comment]
Any solution?

**Comment by rjzupkoii** [comment]
Tried to reproduce the error described and was unable to. A fix to the underlying libraries and pages might have corrected problem, or more information may be needed to reproduce it.

**Comment by rjzupkoii** [comment]
It's been over two weeks with no updates, so I'm going to go ahead and close this issue as unreproducible.
