### ISSUE TITLE
Missing whitespace in Medium social field in the sidebar

### ISSUE THREAD

**Issue by jaideep156** [academicpages/academicpages.github.io#2316]
**Describing the bug**
In the sidebar socials, when I put my medium link, there is no space between the Medium logo and "Medium" text itself.

**To Reproduce**
1. Fork the academicpages.github.io repository.
2. Click on `_config.yml` 
3. Scroll down to `medium` and insert your profile link in quotes. For eg.: "medium.com/@yourusername"
4. Push your changes

**Expected behavior**
It should show the `Medium logo <SPACE> Medium` like other socials above. 

**Screenshots**
![Screenshot 2024-08-08 112143](https://github.com/user-attachments/assets/155522db-23de-442f-a398-275e3f648b8b)

**Desktop:**
 - OS: Windows
 - Browser: Chrome
 - Version: 127.0.6533.90

**Comment by rjzupkoii** [comment]
I just pushed a small update that should fix this, let me know if it works.

**Comment by jaideep156** [comment]
Fixed! Thank you!
