### ISSUE TITLE
Portfolio items not sorting by most recent date

### ISSUE THREAD

**Issue by jaideep156** [academicpages/academicpages.github.io#2317]
**Describe the bug**
In `_portfolio` folder, I have two files `2024-05-23-ner.md` & `2024-06-28-summarizer.md`. When I push the changes, the content of `2024-05-23-ner.md` appears first and then `2024-06-28-summarizer.md`

**To Reproduce**
1. Fork the academicpages.github.io repository.
2. Click on `_portfolio` folder
3. Create two files namely `2024-05-23-ner.md` & `2024-06-28-summarizer.md` write some content in it. 
4. Push the changes

**Expected behavior**
Content of `2024-06-28-summarizer.md` should appear first & then `2024-05-23-ner.md` since it has the most recent date.

Please help me to either:
- Sort it in my requested order (Most recent first) OR 
- Remove the date field completely & display it in the order I want. 

**Additional Context**
Content inside `2024-05-23-ner.md` file:
```
---
title: "Named Entity Recognition & Topic modeling of news articles"
excerpt: "This project performs NER.<br/><img src='/images/ner.gif'>"
collection: portfolio
---

Check it out on GitHub.
```

Content inside `2024-06-28-summarizer.md` file: 
```
---
title: "verge-digest: AI News Summarizer"
excerpt: "Text summarization.<br/><img src='/images/demo.gif'>"
collection: portfolio
---

Check it out on GitHub
```

**Screenshots**
![issue](https://github.com/user-attachments/assets/6acd1771-0ba8-4b9d-814c-c672d5775a3f)

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - Browser: Chrome
 - Version: 127.0.6533.100

**Comment by rjzupkoii** [comment]
This is actually the default behavior for the portfolio and requires a bit of customization to reverse the order. The wiki has been updated to address how to do this: [Order of Portfolio](https://github.com/academicpages/academicpages.github.io/wiki/Customizing-the-content-on-your-site#order-of-portfolio)
