### ISSUE TITLE
Published website showing a page that does not exist

### ISSUE THREAD

**Issue by jaideep156** [academicpages/academicpages.github.io#2318]
**Describe the bug**
After removing a navigation field in `_data/navigation.yml`, it still shows the default page of that navigation field.

**To Reproduce**
1. Fork the academicpages.github.io repository.
2. Go to `_data/navigation.yml`
3. Delete the following code block:
```
  - title: "Publications"
    url: /publications/

  - title: "Talks"
    url: /talks/ 
```
5. Publish changes

**Expected behavior**
When I go to `myusername.github.io/publications` or `myusername.github.io/talks` , it should show the `404.md` page since these pages do not exist (as we removed both the fields from `_data/navigation.yml` 

Please help me to:  
Redirect ANY links apart from `/CV` , `/year-archive` , `/portfolio` redirect to the `404.md` page.

**Screenshots**
![issue](https://github.com/user-attachments/assets/75aea717-4971-4f0b-ad10-930d7d3db0f4)

**Desktop Information**
 - OS: Windows 11
 - Browser Chrome
 - Version: 127.0.6533.100

**Comment by rjzupkoii** [comment]
Updating the `_data/navigation.yml` doesn't prevent the collection from being rendered by the template, you still need to remove the actual data from the repository prior to deployment. Please see [Adjusting Collections Included](https://github.com/academicpages/academicpages.github.io/wiki/Customizing-the-layout-of-your-site#adjusting-collections-included) for more information.
