### ISSUE TITLE
No scrollbar to the long table of content

### ISSUE THREAD

**Issue by mendax1234** [academicpages/academicpages.github.io#2383]
**Describe the bug**

I found that if my toc is too long, there will still be no scroll bar for it.

**To Reproduce**

Go to this [website](https://mendax1234.github.io/CS1010-Vim-Unix/) 

**Expected behavior**

I expect that there will be a scrollbar for it.

**Screenshots**

![image](https://github.com/user-attachments/assets/94f00075-651b-4efe-8d54-17cbc882a66c)

**Desktop (please complete the following information):**
- OS: windows
- Browser: chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rjzupkoii** [comment]
This doesn't look like a component that is included in the template, plus we would need source code (or access to a repository) that reproduces the issue. However, it is worth noting that given how many items are in that TOC, most UI/UX guidelines would suggest collapsing some of the subsections down a bit.
