### ISSUE TITLE
PDF viewer

### ISSUE THREAD

**Issue by lexeyV** [academicpages/academicpages.github.io#242]
Does anyone have any suggestions on how to integrate a pdf viewer into CV page?

**Comment by bensdm** [comment]
is it what you are looking for?
<embed src="https://username.github.io/files/cv.pdf" type="application/pdf" width="600px" height="500px" />

**Comment by lexeyV** [comment]
Did you mean to include something in your message?

**Comment by bensdm** [comment]
sorry forgot quotes

**Comment by lexeyV** [comment]
That's exactly what I was looking for. Thanks!
