### ISSUE TITLE
Strange Location Marker

### ISSUE THREAD

**Issue by drmenguin** [academicpages/academicpages.github.io#244]
Why does the font awesome map marker look strange? It doesn't have a "hole" as it should: https://fontawesome.com/v4.7.0/icon/map-marker

**Comment by carlosluis** [comment]
I found a solution to this problem: simply change [this line](https://github.com/academicpages/academicpages.github.io/blob/25c30de2b4ce3e3f23559384699bb4b9865d6473/_includes/author-profile.html#L26) on the author_profile.html by 

` <li><i class="fa fa-fw fa-map-marker-alt" aria-hidden="true"></i> {{ author.location }}</li>`

This other icon does show the hole as you would expect from a "location" icon

**Comment by rudynicolop** [comment]
How do I change the color of the map marker?

Thanks!

**Comment by rjzupkoii** [comment]
This might require a new version of the font library, shifting to the next milestone.

**Comment by rjzupkoii** [comment]
Updated to Font Awesome v6 and changed the map icon.
