### ISSUE TITLE
Dockerfile installation error

### ISSUE THREAD

**Issue by zoelesv** [academicpages/academicpages.github.io#2488]
**Describe the bug**
Failure to install Bundler and dependencies during Docker build process.

**To Reproduce**
1. Clone the repository: git clone [<https://github.com/academicpages/academicpages.github.io>]
2. Run: docker build -t jekyll-site .

**Expected behavior**
[+] Building 1.9s (8/9)                                    docker:desktop-linux
=> CANCELED [1/5] FROM docker.io/library/ruby:3.2@sha256:f91b6fc160a5a82  0.0s
=> CACHED [2/5] RUN apt-get update && apt-get install -y     build-essen  0.0s
=> CACHED [3/5] WORKDIR /usr/src/app                                      0.0s
=> ERROR [4/5] COPY Gemfile Gemfile.lock ./                               0.0s

**Screenshots**
<img width="784" alt="Screenshot 2024-10-01 at 9 17 24 PM" src="https://github.com/user-attachments/assets/40f38532-8e40-4813-9733-c1e397ad3b94">

**Desktop (please complete the following information):**
 - OS: macOS 13.0.1

**Comment by JohannaXiao** [comment]
Same for me

**Comment by JohannaXiao** [comment]
I solved this by changing `COPY Gemfile Gemfile.lock ./` to `COPY Gemfile ./`

**Comment by rjzupkoii** [comment]
Pull request has been merged, please let me know if this fixes the problem.

**Comment by zoelesv** [comment]
> Pull request has been merged, please let me know if this fixes the problem.

Thank you. Problem solved!
