### ISSUE TITLE
[Deploy]Cannot deploy it on github

### ISSUE THREAD

**Issue by yuanze1024** [academicpages/academicpages.github.io#2591]
**Describe the bug**
I'm using your repo as a template, and adding my stuffs on it. 
When deployed to github using github default Jekyll action, the page is really weird. It turns out that I have trouble getting main.css and a lot of other files.

In fact, this behavior is really like what I saw using docker to deploy it on my server. (where it goes something like 0.0.0.0 is not valid). So I wonder if there is a deploy script that I've missed?

**To Reproduce**
1. You can simply fork this repo, and deploy it using default action. 

**Expected behavior**
The result should look like my https://yuanze.me/.

**Screenshots**
You can check my https://yuanze.me/ or https://yuanze1024.github.io/academicpages/.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser safari
 - Version does not matter

**Additional context**
Please ask me if more details are needed to fix it.

**Comment by rjzupkoii** [comment]
It looks like your configuration is incorrect - in your `_config.yml` file you should have a URL that is something like `[your GitHub username].github.io`. Aliasing to a different domain is possible, but it's best to set that up after everything has been setup correctly.
