### ISSUE TITLE
Bug: Personal contact and social media list disappear after switching to mobile view and then switch back

### ISSUE THREAD

**Issue by hosiet** [academicpages/academicpages.github.io#2637]
On desktop browsers, after dragging the window to force the website to switch to mobile view, click the "Follow" button, and switch back, the personal contact and social media list will disappear.

**To Reproduce**
Steps to reproduce:

1. On a desktop OS (e.g., Window 11), open https://academicpages.github.io/ with Chrome v131. Ensure that the webpage is opened roughly in 16:9 ratio (see screenshot 1).
2. Drag the right window edge to the left side, until the "Follow" button appears (see screenshot 2).
3. Click the "Follow" button (see screenshot 3).
4. Click the "Follow" button again (see screenshot 4).
5. Drag the right window edge back and restore a 16:9 ratio. You will find that the personal contact and social media list disappeared (see screenshot 5).

**Expected behavior**
After the 5 steps, the website should restore to the original condition.

**Screenshots**

Screenshot 1:
![image](https://github.com/user-attachments/assets/d28c4b47-7710-4c4e-90ff-d2843289fc7c)

Screenshot 2:
![image](https://github.com/user-attachments/assets/d9ee6355-fd9c-419f-a9ae-52831e4512e1)

Screenshot 3:
![image](https://github.com/user-attachments/assets/fb5b48c0-1772-4092-9f6b-375b618d8619)

Screenshot 4:
![image](https://github.com/user-attachments/assets/80f8e697-6336-4ee6-9da3-9d011e2e7ebd)

Screenshot 5 (buggy!):
![image](https://github.com/user-attachments/assets/26f5826c-de78-4aea-9f82-98de5871f0af)

**Comment by rjzupkoii** [comment]
Bug fix pushed, but is is _fairly fragile_ since changing the `$large` breakpoint in `_scss/_variables.scss` requires a change to `scssLarge` in `js/assests/_main.js` and rebuilding the minified JavaScript using ` npm run uglify`
