### ISSUE TITLE
How to add favicon to the website?

### ISSUE THREAD

**Issue by ghost** [academicpages/academicpages.github.io#264]
How to add favicon to the website?

**Comment by stevenbitner** [comment]
I'm pretty sure you just have to create your favicon in various resolutions, e.g. 16x16 and save it as `images/favicon-16x16.png` or whatever resolution. The default for web browsers is `images/favicon.ico`

**Comment by voidism** [comment]
You need to remove all annoying `?v=M44lzPylqQ` strings in `_includes/head/custom.html` also.

**Comment by gduarter** [comment]
One silly question: how did you get rid of the original one? I got a new series of favicon files copied to `images`, but I still have the original stylized M.

**Comment by stevenbitner** [comment]
If you committed and pushed your changes, it's probably just browser cache. Have you tried clearing cache and reloading?

**Comment by BUAAZFK** [comment]
How to change the title to a fixed string beside the logo of website?
