### ISSUE TITLE
"redirect_from" is broken in default format

### ISSUE THREAD

**Issue by tomrannosaurus** [academicpages/academicpages.github.io#2644]
**Describe the bug**
"redirect_from" is broken in default format. Pages do not redirect. 

**To Reproduce**
1. Go to: https://academicpages.github.io/resume

**Expected behavior**
Should redirect to https://academicpages.github.io/cv, but does not

**FIX**
To fix, add jekyll-redirect-from to Gemfile, and   - jekyll-redirect-from to _config.yml under 'plugins:' and 'whitelist:'
Fix is implimented here:
https://github.com/tomrannosaurus/tomrannosaurus.github.io/blob/master/_config.yml
https://github.com/tomrannosaurus/tomrannosaurus.github.io/blob/master/Gemfile

**Comment by tomrannosaurus** [comment]
a pull request has been issued that resolves this bug:
https://github.com/academicpages/academicpages.github.io/pull/2645

**Comment by rjzupkoii** [comment]
Good catch, thanks for the pull request!
