### ISSUE TITLE
How to add arxiv to left sidebar?

### ISSUE THREAD

**Issue by mgonch** [academicpages/academicpages.github.io#271]
I would like to add my personal arxiv to the left sidebar on the landing page. Is there any way to do so?

**Comment by MarkoShiva** [comment]
Well not without manually messing with code.
However if you do want to change and add arxiv or any other website to left collumn you should edit a .config.yml to include a part for arxiv
Also you should change the author profile to include link element for new added option for arxiv.

You can check my changes on the commit https://github.com/MarkoShiva/MarkoShiva.github.io/commit/3c735edfbf89a3b7bb21a2073ed17396c9c4f60a

Ignore change in projects.md as that one wasn't relevant to adding a hackerrank for example to the list.

However make sure to research and include proper url for arxiv in proper format and add your username to the config.yml

**Comment by JuanFMontesinos** [comment]
Hi @MarkoShiva, I could do it but I was wondering how to set the icon/logo together with the item.

**Comment by mprobson** [comment]
Check out the linked Minimal Mistakes [documentation](https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-author) which points you to Font Awesome icons [search](https://fontawesome.com/v5/search) to find an icon to use.

**Comment by rjzupkoii** [comment]
The arXiv link has been added to the template, but the fonts will need to be updated which is being tracked under #1911
