### ISSUE TITLE
awesome font pdf icon does not work in markdown 

### ISSUE THREAD

**Issue by schrilax** [academicpages/academicpages.github.io#278]
Hello, 
Firstly I wanted to say this is an awesome template for creating academic websites. 

I am unable to make the awesome font pdf icon to render in markdown files. More specifically, I am trying to add awesome font icons to cv.md however either the icon does not properly or at all. I have to say that some icons are rendering but not the awesome font pdf icon which I wanted. Is it an issue specific to markdown files ? Should I try using .html files instead ? 

I have tried using both `<i class="fa fa-file-pdf-o" aria-hidden="true">` and `<i class="fal fa-file-pdf"></i>` but neither worked. I tried the markdown awesome font icon and it worked. I checked in the codebase that the source code base already contains the `fa-solid` files (pdf icons are part of the solid class).

Can someone help or have any suggestions ?

**Comment by rjzupkoii** [comment]
Might be related to #413
