### ISSUE TITLE
Page Width

### ISSUE THREAD

**Issue by gicheonkang** [academicpages/academicpages.github.io#292]
Hi, I want to extend the width of the main body. What value should I change?

**Comment by vstadnytskyi** [comment]
Did you figure out how to do that?

**Comment by gicheonkang** [comment]
@vstadnytskyi yeah, please refer to the thread below :)
https://github.com/mmistakes/minimal-mistakes/issues/384

**Comment by cdhx** [comment]
So how to enlarge the width of the main page, the link is about adjusting the sidebar.
