### ISSUE TITLE
Dark style

### ISSUE THREAD

**Issue by AntoineSoetewey** [academicpages/academicpages.github.io#297]
Hi, did anyone manage to include a dark style option ?
Thanks in advance !

**Comment by MarkoShiva** [comment]
That is a good idea

**Comment by AntoineSoetewey** [comment]
With some help from https://derekkedziora.com/blog/dark-mode I finally managed to add the possibility to switch to a dark theme. Hope it helps!

**Comment by ctuni** [comment]
Hi @AntoineSoetewey I know this issue is closed but could you give details on how you managed to add the switch without breaking the rest of the SCSS of the page? I could add the switch but then the rest of the site gets broken :sweat_smile:

**Comment by AntoineSoetewey** [comment]
> Hi @AntoineSoetewey I know this issue is closed but could you give details on how you managed to add the switch without breaking the rest of the SCSS of the page? I could add the switch but then the rest of the site gets broken 😅

Hello @ctuni,

This was a long time ago so to be honest I don’t remember, except that I got help from the website mentioned above to add this feature.

Since then, I have switched to another theme, so I cannot even show you the code to make it work for your site.

If you have the time, you could always check previous versions of my website via my repository (https://github.com/AntoineSoetewey/antoinesoetewey.com), but good luck because it’s quite a long time ago and there are quite a lot of commits.

Hope this helps.

**Comment by ctuni** [comment]
Hi @AntoineSoetewey Thank you for your answer! I understand that it might be difficult but I'll try nonetheless. Thanks for pointing me in the right direction!

**Comment by ShamanthNyk** [comment]
Hi, any updates on this?
