### ISSUE TITLE
How to adjust page title shown in browser tab and google search results?

### ISSUE THREAD

**Issue by kathrinackermann** [academicpages/academicpages.github.io#301]
I have just started to work with academicpages to build my website and it is an amazing template (thanks a lot to the developers!).
However, I struggle with adjusting the page title that is shown in the browser tab. Particularly for the front page, I want to have a different title shown on the front page and in the browser tab (now in my case the text in the browser tab says: "Welcome to my website!", https://kathrinackermann.github.io/). Also, I do not want the title of the front page to be shown in the google search results (what also seems to be the case). Is there any possibility to adjust the text that is shown in the browser tab (of the front page) and the google search results? In my case, that should be something like my name and the affiliation.
Thanks a lot in advance for your help!

**Comment by sidenver** [comment]
If anyone else has this issue, this is the fix that worked for me. I had to change the line in `{site}/_includes/seo.html` that assigns a value to `seo_title`.

Before, it was:

```liquid
{% if page.title %}
  {% assign seo_title = page.title | append: " " | append: site.title_separator | append: " " | append: site.title %}
{% endif %}
```
# Fix

From the above code, I made two changes to get a custom title:

## First, in `{site}/_includes/seo.html`

I changed the above lines to the following:

```liquid
{% if page.title and page.author_profile != true %}
  {% assign seo_title = page.title | append: " " | append: site.title_separator | append: " " | append: site.title %}
{% elsif page.title and page.author_profile == true %}
  {% assign seo_title = "YOUR NEW TITLE HERE" %}
{% endif %}
```
This adds a conditional to check if the page has an `author_profile: true` field.

## Second, in `{site}/_pages/about.md`

In `{site}/_pages/about.md`, I added a field at the top that contains `author_profile: true` (**you might already have it**), so it now looks like:

```markdown
---
permalink: /
title: "YOUR NEW TITLE HERE"
author_profile: true
redirect_from: 
  - /about/
  - /about.html
---
```

Note the `author_profile: true` line (line 4).

Hope this helps! Feel free to ask any questions.
