### ISSUE TITLE
External link in a picture

### ISSUE THREAD

**Issue by jaruizso** [academicpages/academicpages.github.io#31]
I have create a table on the front page with 4 logos (images) and I am tryng to add a link, so people can click on them. However unsuccessfully. 

![captura de pantalla 2017-07-27 a les 11 14 54](https://user-images.githubusercontent.com/12252768/28663168-ddf1d146-72bc-11e7-890f-a407f2c92e26.png)

The pictures look ok on the website with that code, but is there any way to introduce a link on them?

![captura de pantalla 2017-07-27 a les 11 30 53](https://user-images.githubusercontent.com/12252768/28663933-17710e4e-72bf-11e7-81a7-293824f1b38c.png)

I tried with the following and several combinations, but does not work:

`[http://www.epsanet.org](/images/epsa.png)  `

`![http://www.epsanet.org](/images/epsa.png)  `

**Comment by duffrind** [comment]
I do not use this repo, however does the following work?

`[![title](picture.png)](http://link.com/)`

Appears to work in these comments. Try clicking the picture below:

[![link to your github](https://avatars3.githubusercontent.com/u/12252768?v=4&amp;s=88)](https://github.com/jaruizso)

**Comment by jaruizso** [comment]
Yep! it works. Many thanks for your help :)

**Comment by Zijia-Cheng** [comment]
> I do not use this repo, however does the following work?
> 
> `[![title](picture.png)](http://link.com/)`
> 
> Appears to work in these comments. Try clicking the picture below:
> 
> [![link to your github](https://avatars3.githubusercontent.com/u/12252768?v=4&s=88)](https://github.com/jaruizso)

Hi, I wonder is there a way to change the size and position of figures on the webpage through coding in the markdown file, like blog_post? Thanks!
