### ISSUE TITLE
email updates from cloned repositories 

### ISSUE THREAD

**Issue by vstadnytskyi** [academicpages/academicpages.github.io#312]
It seems to me that every time someone clones the repository and start updating it, I get emails. These emails notify me that there are changes in a cloned repository. How do I turn it off? I want to see changes in the main repository and not cloned ones.

**Comment by rjzupkoii** [comment]
Now that Academic Pages has shifted to being a template repository, new users for fork the template should not receive emails regarding updates to the repository by other users.
