### ISSUE TITLE
line break not working

### ISSUE THREAD

**Issue by AliAlsaqqa** [academicpages/academicpages.github.io#316]
I tried doing a line break, it is not working (shows as a single line). I tried all of the following

bio              :  |
                        "Hello
                        World"
----------------------------------
bio              :  >
                        "Hello
                        World"
----------------------------------
bio              :  "Hello
                        World"
---------------------------------
bio              :  "Hello \n World"

None of them produced a line break. What is wrong?

**Comment by AntoineSoetewey** [comment]
have you tried `<br>`?

**Comment by shadab-entrepreneur** [comment]
Try <br/>

**Comment by AliAlsaqqa** [comment]
Worked great, thanks.
