### ISSUE TITLE
Blog post title and previews not showing up

### ISSUE THREAD

**Issue by mrengler** [academicpages/academicpages.github.io#326]
When I add blog posts following the same format, neither a section for the new year (2020) nor the titles/previews for the posts appear, but I know the posts are added and the estimated reading time still appears, like so:

<img width="402" alt="Screen Shot 2020-02-13 at 9 18 14 AM" src="https://user-images.githubusercontent.com/43390331/74449284-fcd6d580-4e41-11ea-9e64-286cc51a6cc2.png">

I am led to believe that this should happen automatically based on the example page, but I could also be missing something as I don't know much about web development. Thanks!

**Comment by snehjp2** [comment]
Hi, I'm having the same issue.  Did you ever find a resolve?

**Comment by WEIYujie1996** [comment]
same issue, Did you ever find a resolve?
