### ISSUE TITLE
Support latex equations with MathJax

### ISSUE THREAD

**Issue by rcalsaverini** [academicpages/academicpages.github.io#33]
It shouldn't be difficult to add latex support with MathJax. I think a good chunk of the users would be interested in something like this.

**Comment by rcalsaverini** [comment]
Well, I managed to make it work for me by just adding the following snippet to the file `_includes/head/custom.html`:

```html
<script type="text/x-mathjax-config"> MathJax.Hub.Config({ TeX: { equationNumbers: { autoNumber: "all" } } }); </script>
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    tex2jax: {
      inlineMath: [ ['$','$'], ["\\(","\\)"] ],
      processEscapes: true
    }
  });
</script>
<script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" type="text/javascript"></script>
```

**Comment by JayanthRR** [comment]
@rcalsaverini Thanks for the above snippet.

**Comment by jasonyanglu** [comment]
This snippet doesn't work for the display math which starts and ends with $$. Anyone can fix it ?

**Comment by rcalsaverini** [comment]
Hi @jasonyanglu, the snippet above should work for display math using `$$math here$$`. Can you please check if there are trailing spaces before or after your equation? Maybe this is the problem.

**Comment by rcalsaverini** [comment]
Ok, I just tested here and my setup works even with trailing spaces. It's probably another problem. Can you check if equations do get rendered if they're enclosed in `$...$`, `\[...\]` and `\(...\)`?

**Comment by jasonyanglu** [comment]
Hi @rcalsaverini, thanks for you quick response. I tried and found that it works only if the latex content is in the same line with $$ like:

$$z_{1-\alpha/2}\sigma\sqrt{2/n}$$

If it is writen as 

$$
z_{1-\alpha/2}\sigma\sqrt{2/n}
$$

Then it does not work. However, there still a problem that the align environment does not work:

$$\begin{aligned}H_0:&\mu_0-\mu_1=0\\H_1:&\mu_0-\mu_1=\delta\end{aligned}$$.

Can you help figure it out? Thanks a lot.

**Comment by rjzupkoii** [comment]
MathJax has been bumped to version 3.0 and I've added some notes to the [template's guide page](https://academicpages.github.io/markdown/) since markdown causes some minor issues with it.
