### ISSUE TITLE
post not showing up, no error produced

### ISSUE THREAD

**Issue by mberaha** [academicpages/academicpages.github.io#338]
Hi everyone, I'm trying to add a post to my website.

The post is basically a jupyter notebook, that I into markdown using `jupyter nbconvert --to markdown` and then copy-pasted it into a blog post.

The link for such post is:

https://github.com/mberaha/mberaha.github.io/blob/master/_posts/us-airline-data.md

Even after 30 minutes, the post does not show up, but I get no failure notification from jekyll!

**Comment by naga-karthik** [comment]
Hey! I had the same problem as you. I might just have a solution for this. You have to follow the naming convention that is already there for each markdown file. That is, "year-month-date-your-blog-title.md". In other words, the path that you set in the "Permalink" option inside each ".md" file has to be sorted according to the year, month and so on.
Let's say that you have written your blog on 1st April 2020, then the Permalink for your blog would be like this: "/posts/2020/04/us-airline-data/"
Once this is done, you should see the update in a few minutes.
