### ISSUE TITLE
How to add visitor map to my personal website

### ISSUE THREAD

**Issue by min-chao** [academicpages/academicpages.github.io#345]
How to add visitor map that shows the number of visitors worldwide who visit my github.io website?

**Comment by min-chao** [comment]
Like the world map on the upper right of this website:
[http://www.shichuan.org/ShiChuan_ch.html](url)

**Comment by CaucherWang** [comment]
This function is interesting. Why not add to the plan? @rjzupkoii

**Comment by rjzupkoii** [comment]
@CaucherWang It is an interesting feature, but I'm not sure a lot of people would actually make much use of it, which makes it outside the scope of the template itself. However, if you start a thread over in the [disucssions](https://github.com/academicpages/academicpages.github.io/discussions) you might find some people that are also interested in implementing one.
