### ISSUE TITLE
Masthead and footer background color

### ISSUE THREAD

**Issue by imperfectdark** [academicpages/academicpages.github.io#360]
How can I change the masthead and footer background colors? Whenever I try directly edit the masthead and footer css files to add a “background: <color>;” tag, not all of the header or the footer is colored in (e.g, a white box remains in the header to the right of the final link). 

Any help would be much appreciated! I only want to change the color of the header and footer, NOT the sidebar or the body.

Thank you for the help!

**Comment by torimcd** [comment]
I was able to do this in the masthead by adding a "background" tag to both the masthead css file and **also** the navigation css file, under .greedy-nav
