### ISSUE TITLE
Minor style adaptations (font size, font face, background color)

### ISSUE THREAD

**Issue by schmitt-muc** [academicpages/academicpages.github.io#366]
How can I adapt the style of the template a little bit for sake of individualization? I'd like to make the standard font size a bit smaller and maybe change the font face to something more exciting than Arial. Also, maybe a light gray-shade background color would be nice. I can't seem to find those options, though.

**Comment by richard-warren** [comment]
I just figured this out for my page. Try adjusting the global font variables [here](https://github.com/academicpages/academicpages.github.io/blob/master/_sass/_variables.scss).
