### ISSUE TITLE
 run locally on windows 7

### ISSUE THREAD

**Issue by chituma110** [academicpages/academicpages.github.io#37]
How to run the following line on the win7
1.Make sure you have ruby-dev, bundler, and nodejs installed: sudo apt install ruby-dev ruby-bundler nodejs
2.Run bundle clean to clean up the directory (no need to run --force)
3.Run bundle install to install ruby dependencies. If you get errors, delete Gemfile.lock and try again.
4.Run bundle exec jekyll serve to generate the HTML and serve it from localhost:4000

**Comment by nightlessbaron** [comment]
The above solution didn't really work for me. I will post a solution that sort of worked for me.
1. Install Ruby from here: [https://rubyinstaller.org/](https://rubyinstaller.org/)
2. Once this is done, open the command prompt and go to the directory where your project is.
3. Now, go to Gemfile and add `gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]` before plugins (around line 20).
4. (Skip this step during the first iteration.) Delete Gemfile.lock
5. `bundle install`
6. `gem uninstall eventmachine --force`
7. `gem install eventmachine --platform ruby`
8. `bundle exec jekyll serve`
9. If this doesn't work, try step 4) and repeat.
It should work like a charm. Drop a question in case this doesn't work.
