### ISSUE TITLE
Does this repo support a more flexible way to arrange the publications page?

### ISSUE THREAD

**Issue by entslscheia** [academicpages/academicpages.github.io#371]
Basically, I want two things: 1) a friendly way to display the authors list for every publication 2) group publications into several different sections, i.e., conference papers, journal papers and preprint.
For now I haven't found a convenient way for doing those. Anyone has any suggestion on this?

Many thanks!

**Comment by ShangwenWang** [comment]
@entslscheia Hello, I also have the concern.
Have you resolved it? I met an error when editing my own publications
