### ISSUE TITLE
Code icon in syntax boxes not rendering

### ISSUE THREAD

**Issue by jayrobwilliams** [academicpages/academicpages.github.io#388]
The Font Awesome code icon (</>) at the top right of syntax boxes is not rendering and appears as a blank unicode box.

<img width="784" alt="Screen Shot 2020-06-20 at 9 38 42 AM" src="https://user-images.githubusercontent.com/12078284/85204162-827efc00-b2e0-11ea-887e-d31c23e8f32b.png">

I have fixed this in f77695356 and will be submitting a PR shortly.

<img width="788" alt="Screen Shot 2020-06-20 at 9 36 07 AM" src="https://user-images.githubusercontent.com/12078284/85204177-9aef1680-b2e0-11ea-834d-1227f8cc939d.png">

**Comment by jayrobwilliams** [comment]
@staeiou could you please take a look at this issue and #389 to fix it?

**Comment by rjzupkoii** [comment]
Fixed with pull request #389
