### ISSUE TITLE
_publications, navigation.yml, about.md not updating properly?

### ISSUE THREAD

**Issue by matthewhholden** [academicpages/academicpages.github.io#39]
For some reason when I update the forked version of the site in my repository, everything does not seem to update (except for what is in the _config.yml file). I'm following the basic differences in the documentation provided here http://archive.is/3TPas. Is this a bug or am I doing something completely wrong. Sorry I'm quite new to github, so its all a bit unfamiliar to me and a bit hard for me to tell what I am doing wrong.

The files I have modified are only: 
_config.yml (which worked), 
_publications: adding files to it  (didn't work), 
_pages/about.md: modifying the text in it (didn't work) 
_data/navigation.yml: deleting headings from  (didn't work)

strangly the about.md file updating did work several hours ago, but when I retried recently it didn't work

**Comment by matthewhholden** [comment]
yml date issue

**Comment by thanhnguyentang** [comment]
@matthewhholden : Hi, I changed _data/navigation.yml directly in Github repos but the change does not reflect on the website. Do you mind sharing how did you solve it? Thanks.

**Comment by Harrypotterrrr** [comment]
Hello,
I have met the same problem that whenever I rename cv.md you provided to cv_bak.md, upload my cv.md, and use `bundle exec jekyll serve` to watch the changes, the website and static html generated doesn't change.
Could you help me to figure it out? Thanks!
