### ISSUE TITLE
Adding custom domain

### ISSUE THREAD

**Issue by anjalibhavan** [academicpages/academicpages.github.io#395]
Sorry if this is a very obvious query or something.
I have till now had the url anjalibhavan.github.io, and would like to change it to anjalibhavan.com. I added a CNAME file and changed the url in config.yml, but my new url still does not load; but the older anjalibhavan.github.io redirects to anjalibhavan.com (and doesn't load). Would appreciate some help. Are there some other steps to be taken?

**Comment by YubinXie** [comment]
did you figure it out? thanks!
