### ISSUE TITLE
No line breaks in rendered html causes equation problems

### ISSUE THREAD

**Issue by richard-warren** [academicpages/academicpages.github.io#397]
For some reason the source code for rendered pages has no line breaks, e.g. the source for [this page](https://academicpages.github.io/). Compare this to the [source html formatting for the original minimal mistakes sites](https://mmistakes.github.io/minimal-mistakes/). The line breaks appear when building the site locally, but not when they are build on github.

The lack of line breaks causes certain MathJax syntax to break, e.g. \begin{aligned}... See [this issue](https://github.com/mathjax/MathJax/issues/2274) for an example.

Is there a way to recover the line breaks in the html rendering so that the equations work?

**Comment by richard-warren** [comment]
Problem solved. AcademicPages uses agressive [html compression](https://www.digitalocean.com/community/tutorials/jekyll-compress-html) but bypasses the compression when running locally. This can cause issues with MathJax rendering. To solve:

- Changing `envs: development` to `envs: ` [here](envs: development) so the compression will be applied locally as well. Now the page will look the same locally and on github.
- Change `clippings: all` to `clippings: pre`  [here](https://github.com/academicpages/academicpages.github.io/blob/25c30de2b4ce3e3f23559384699bb4b9865d6473/_config.yml#L309) to preserve line breaks. Now the equations work!

**Comment by SamGRosen** [comment]
I ran into this same issue but @richard-warren 's solution did not work for me. I fixed my issue by adding `blanklines: true` to compress html instead:

```
compress_html:
  clippings: all
  blanklines: true
```

According to the [docs](http://jch.penibelst.de/#blanklines) of the compressor used, if the `blanklines` parameter is true then the only new lines that will be removed are ones that are totally blank.
