### ISSUE TITLE
Possible to remove the sidebar?

### ISSUE THREAD

**Issue by yukitakahashi1** [academicpages/academicpages.github.io#403]
Hi,
I really like this theme's appearances and functions, but I want to include my profile photo in the main text instead of side bar, like academic-minima theme (https://github.com/academicbio/academic-minima). Is it possible to remove the sidebar?

**Comment by yingjun-mou** [comment]
![image](https://user-images.githubusercontent.com/29914918/108392500-c82df480-71e0-11eb-8a27-33878778a13d.png)

We can turn on/off the side bar by setting the boolean author_profile to true/false. They are in the _config_yml at top level of the repo. I think you can also go to each specific page, and overwrite that boolean at beginning of the html code.

![image](https://user-images.githubusercontent.com/29914918/108392994-37a3e400-71e1-11eb-96f6-1f449512cc10.png)

**Comment by yukitakahashi1** [comment]
Thank you. I turned off the sidebar!
