### ISSUE TITLE
Add Chinese in ui-text.yml

### ISSUE THREAD

**Issue by luyaozou** [academicpages/academicpages.github.io#404]
Would it be welcomed to add a Chinese (simplified) version in `ui-text.yml`? I'd be interested in doing that.

**Comment by rjzupkoii** [comment]
This is definitely something that can be done, but the big barrier is going to be finding someone that can supply the correct translations.

**Comment by YanY-Henry** [comment]
In the pull request #2144, I finished the Chinese translation of `ui-text.yml` (both simplified and traditional). Hope it can help!
