### ISSUE TITLE
Aligned equations with MathJax cannot refered

### ISSUE THREAD

**Issue by RuihongQiu** [academicpages/academicpages.github.io#405]
Hi, I successfully input equations including single-line and multi-line equations.

However, I can only use `\ref{}` to refer to single-line equations.
while for multi-line equations, it shows:
![image](https://user-images.githubusercontent.com/17882988/88451905-c647c100-ce9d-11ea-83f2-bfe7c2424c9c.png)

Does anyone have ideas about it?

Thank you!

**Comment by rjzupkoii** [comment]
Appears to be related to #33
