### ISSUE TITLE
Academicons not visible on the page

### ISSUE THREAD

**Issue by katreparitosh** [academicpages/academicpages.github.io#413]
Hello,

I was beautifying my website, but suddenly the "academicons" have stopped appearing. The links are active, but all academicons are missing.

![image](https://user-images.githubusercontent.com/42617598/89637357-a9f94a80-d8c7-11ea-8539-837b73378399.png)

[Link to my repo](https://github.com/katreparitosh/katreparitosh.github.io)

- I updated the academicons version to v1.8.6 
- Checked if U commented anything in custom.html 

I can't seem to find the bug. Kindly help.

**Comment by ndimhypervol** [comment]
Having the same problem. Just did a clean fork and still the icons don't render when I run `bundle exec jekyll serve`. Any idea how to fix this? Thanks.

<img width="135" alt="Screen Shot 2020-12-07 at 12 24 55" src="https://user-images.githubusercontent.com/2090459/101306022-3a03cc80-3887-11eb-806c-9965d764ed4b.png">

**Comment by ndimhypervol** [comment]
> Having the same problem. Just did a clean fork and still the icons don't render when I run `bundle exec jekyll serve`. Any idea how to fix this? Thanks.
> 
> <img alt="Screen Shot 2020-12-07 at 12 24 55" width="135" src="https://user-images.githubusercontent.com/2090459/101306022-3a03cc80-3887-11eb-806c-9965d764ed4b.png">

Okay, just realized that if I click on any link, the icons return, even for the main page. Must be a glitch when first rendering?

**Comment by rjzupkoii** [comment]
This might be a [CORS error](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors) due to how the icons are served, will double check.

**Comment by rjzupkoii** [comment]
Attaching this to #1905 since this is likely the same problem. It also appears that the problem might have been resolved by the latest version of the libraries.
