### ISSUE TITLE
Layout of page not showing properly as sample 

### ISSUE THREAD

**Issue by rongjinutd** [academicpages/academicpages.github.io#438]
Have no ideas that why the page showing as plain text without the same layout as sample's. Should I have config on CSS or HTML or JS?

**Comment by rongjinutd** [comment]
Solved.

**Comment by namespace-Pt** [comment]
How do you solved? @rongjincsuf

**Comment by rongjincsuf** [comment]
> How do you solved? @rongjincsuf

Couldn't remember clearly. Probably create layout manually at that time.
