### ISSUE TITLE
Using pagination

### ISSUE THREAD

**Issue by Jing-Luo** [academicpages/academicpages.github.io#44]
Hi!

I'm trying to use this template but I don't know how to use it with pagination.

with:

```
paginate: 5
paginate_path: "/page:num/"
in _config.yml file 

```
I always receive the warning Pagination: 

`Pagination is enabled, but I couldn't find an index.html page to use as the pagination template. Skipping pagination.`

I saw that there is a file called "pagination.html". How should I use it with the archive template?

Thank you!

**Comment by bertolinocastro** [comment]
It looks like they've removed this `pagination.html` from the source tree.

**Comment by rjzupkoii** [comment]
Looking at this again, it might have been a bug that was addressed with the changes since it was first reported.
