### ISSUE TITLE
site built fails with https

### ISSUE THREAD

**Issue by eborbath** [academicpages/academicpages.github.io#441]
I followed the steps outlined on this page: https://docs.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https to have a secure connection when loading the website. However, after I enforce https:// the website does not load correctly, basically the stylesheet fails. Did this come up before? Any idea how to fix it?

**Comment by arjunramani3** [comment]
I have the same issue!

**Comment by zechengli96** [comment]
same here

**Comment by layumi** [comment]
same here

**Comment by layumi** [comment]
Hi all, I found the solution. 
It is due to the `https` loading the css of `http`. You may open the webpage console (such as Chrome) to see this error. 
The solution is to change the config file.  In my case, I change the `url` as my domain to solve the problem:
```
url                      : "//zdzheng.xyz" 
```
