### ISSUE TITLE
Free space on the left

### ISSUE THREAD

**Issue by adhitir** [academicpages/academicpages.github.io#442]
Hello,

I'm trying to develop my website, https://adhitir.github.io/adhitiraman.github.io//
There's a lot of free space on the left. Would it be possible to get rid of the space and just have the text in the "about" section extend into it?

Second question, how does one go about changing the text style?

**Comment by pecey** [comment]
For both of these things, you can play with scss files located in the _sass folder.

**Comment by yingjun-mou** [comment]
Hi @adhitir! Wondering would you able to fix the issue of the free space on the left? I counldn't locate which scss file I need to modify in order to fix the issue. And now even I turned my author_profile off, there is still a large portion of empty space on the left.
