### ISSUE TITLE
Publication and teaching entries in CV should be ordered reversely in time

### ISSUE THREAD

**Issue by geoalchimista** [academicpages/academicpages.github.io#45]
Publication list is ordered reversely in time (recent publication first) in the "Publications" page, but not so in the "CV" page.

In `publications.md`
```
{% for post in site.publications reversed %}
  {% include archive-single.html %}
{% endfor %}
```

In `cv.md`
```
  <ul>{% for post in site.publications %}
    {% include archive-single-cv.html %}
  {% endfor %}</ul>
```

I think the default style in `cv.md` should be changed to match `publications.md`.

**Comment by ross-dobson** [comment]
Six years after this issue was raised, I want to thank you for helping me realise why my portfolio was sorting the wrong way, after days of tearing my hair out!
