### ISSUE TITLE
Google Scholar dummy url links to websites that try to scam you

### ISSUE THREAD

**Issue by avsaase** [academicpages/academicpages.github.io#456]
The Google Scholar link on https://academicpages.github.io/, http://yourfullgooglescholarurl.com/, links to several different websites that try to scam you with investment scams, "you won a lottery, click here"-scams, etc. Everyone using this theme will change this url of course, but I think it would still be better to change the dummy url to https://scholar.google.com/ for example.

**Comment by rjzupkoii** [comment]
Updated the template to use [Katalin Karikó's](https://en.wikipedia.org/wiki/Katalin_Karik%C3%B3) Google Scholar profile as an example.
