### ISSUE TITLE
Compatibility with SASS 4.0

### ISSUE THREAD

**Issue by joaomlneto** [academicpages/academicpages.github.io#46]
I just forked this for my personal website (looks/behaves amazing! thanks!!) :-)

Disclaimer: I'm not at all familiar with ruby; maybe the problem is on my environment!

When I `$ jekyll serve`, I get thrown a lot of warnings regarding incompatibility with SASS 4.0.
~~~
DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("variable-exists")) instead.
~~~

This seems to have already been fixed in `minimal-mistakes`, and seems to be related to the version of susy bundled in the repo:
https://github.com/mmistakes/minimal-mistakes/issues/1114

**Comment by tgoelles** [comment]
I get the same warnings.

**Comment by ankitshah009** [comment]
Any solution to this problem?
It is annoying to see so many warnings due to the same reason.

**Comment by LeonardoPaccianiMori** [comment]
I have the same exact issue. It is very annoying and it would be really nice if it could be solved.

**Comment by rjzupkoii** [comment]
This appears to be addressed with the latest updates, be sure to run `bundle update` .
