### ISSUE TITLE
Publication Categorization 

### ISSUE THREAD

**Issue by usmanakhtar** [academicpages/academicpages.github.io#48]
How to categorize the Publication as a journal and conferences. When I add the publication based on the journal and the conference it should appear. 

Example.
Publication:
Journal 
1.
2.
Conferences 
1.
2.

how to do this?

**Comment by osnathassner** [comment]
I would like to know how to do this as well. Does anyone even sees these issues? This issue is open for more than 6 months....

**Comment by jw447** [comment]
Yeah trying to figure that out too. May ditch the archive-single page and rewrite the publication page.

**Comment by avonmoll** [comment]
Check out [my fork](https://github.com/avonmoll/avonmoll.github.io) for a quick and dirty way of implementing this. In summary, I put the following line in my publication markdown files

```YAML
pubtype: 'journal'
```

(or `conference` or `academic`). Then, I tweaked `publications.md` to have these sections:
```md
<h2>Journal Articles</h2>
{% for post in site.publications reversed %}
  {% if post.pubtype == 'journal' %}
      {% include archive-single.html %}
  {% endif %}
{% endfor %}

<h2>Conference Papers</h2>
{% for post in site.publications reversed %}
  {% if post.pubtype == 'conference' %}
      {% include archive-single.html %}
  {% endif %}
{% endfor %}

<h2>Academic</h2>
{% for post in site.publications reversed %}
  {% if post.pubtype == 'academic' %}
      {% include archive-single.html %}
  {% endif %}
{% endfor %}
```

It's certainly not efficient -- it loops through all the publications 3 times. However, now they're sorted nicely into these bins.

**Comment by Ashutosh781** [comment]
> Check out [my fork](https://github.com/avonmoll/avonmoll.github.io) for a quick and dirty way of implementing this. In summary, I put the following line in my publication markdown files
> 
> ```yaml
> pubtype: 'journal'
> ```
> 
> (or `conference` or `academic`). Then, I tweaked `publications.md` to have these sections:
> 
> ```
> <h2>Journal Articles</h2>
> {% for post in site.publications reversed %}
>   {% if post.pubtype == 'journal' %}
>       {% include archive-single.html %}
>   {% endif %}
> {% endfor %}
> 
> <h2>Conference Papers</h2>
> {% for post in site.publications reversed %}
>   {% if post.pubtype == 'conference' %}
>       {% include archive-single.html %}
>   {% endif %}
> {% endfor %}
> 
> <h2>Academic</h2>
> {% for post in site.publications reversed %}
>   {% if post.pubtype == 'academic' %}
>       {% include archive-single.html %}
>   {% endif %}
> {% endfor %}
> ```
> 
> It's certainly not efficient -- it loops through all the publications 3 times. However, now they're sorted nicely into these bins.

For another solution to this (maybe more efficient), Check out [my fork](https://github.com/Ashutosh781/Ashutosh781.github.io).

Essentially I create 3 different categories for type of publications, namely 'publications_journal', 'publications_conference' and 'publications_workshop'. You can then basically treat them as 3 different categories and have 3 separate directories for better organization as well. So in each publication markdown files your collection field will change accordingly.

And then just call each category within `publications.md` like this

```
<h2>Conference Papers</h2>


{% include base_path %}

{% for post in site.publications_conference reversed %}
  {% include archive-single.html %}
{% endfor %}

<h2>Workshop Papers</h2>

{% include base_path %}

{% for post in site.publications_workshop reversed %}
  {% include archive-single.html %}
{% endfor %}
```

But do remember you will have to edit `_config.yml`, `_includes/archive-single.html` and `_pages/cv.md`. 
For `_includes/archive-single.html` you can add the below code for each new category

```
{% elsif post.collection == 'publications_journal' %}
    <p>Published in <i>{{ post.venue }}</i></p>
{% elsif post.collection == 'publications_conference' %}
    <p>Published in <i>{{ post.venue }}</i></p>
{% elsif post.collection == 'publications_workshop' %}
    <p>Published in <i>{{ post.venue }}</i></p>
```

**Comment by aauppal** [comment]
> Check out [my fork](https://github.com/avonmoll/avonmoll.github.io) for a quick and dirty way of implementing this. In summary, I put the following line in my publication markdown files
> 
> ```yaml
> pubtype: 'journal'
> ```
> 
> (or `conference` or `academic`). Then, I tweaked `publications.md` to have these sections:
> 
> ```
> <h2>Journal Articles</h2>
> {% for post in site.publications reversed %}
>   {% if post.pubtype == 'journal' %}
>       {% include archive-single.html %}
>   {% endif %}
> {% endfor %}
> 
> <h2>Conference Papers</h2>
> {% for post in site.publications reversed %}
>   {% if post.pubtype == 'conference' %}
>       {% include archive-single.html %}
>   {% endif %}
> {% endfor %}
> 
> <h2>Academic</h2>
> {% for post in site.publications reversed %}
>   {% if post.pubtype == 'academic' %}
>       {% include archive-single.html %}
>   {% endif %}
> {% endfor %}
> ```
> 
> It's certainly not efficient -- it loops through all the publications 3 times. However, now they're sorted nicely into these bins.

Hi avonmol, Thanks for sharing

However, I am unable to get author names, and interactive links to PDF and doi of the papers
