### ISSUE TITLE
Problems with Publications and Talks page

### ISSUE THREAD

**Issue by sarahfocam** [academicpages/academicpages.github.io#493]
I am super new to using github (and all that it entails!) so this is undoubtedly a user error -- but I am having a lot of trouble with the talks and publications pages. After I have entered my personalized information into the publications md files in visual studio code and committed it with github desktop it shows up on my page as: "Published in , 1900" and none of my personal information is showing up. I had a similar issue with the talks pages earlier but it now is working. 

I have attached a screenshot of one of the md files; does anyone see anything obvious that I have entered incorrectly? 
<img width="645" alt="publications example" src="https://user-images.githubusercontent.com/72046337/102098416-0d4a3a80-3ddc-11eb-9e8d-3cf0c91554a8.png">

`---
title: "Review of Xurtan The End of the World and Other Myths, Songs, Charms, and Chants by the Northern Lacondones of Naha by Suzanne Cook."
collection: publications
permalink: /publication/2020-09-17-review-cook
excerpt: 'A review of Suzanne Cook's Xurtan The End of the World and Other Myths, Songs, Charms, and Chants by the Northern Lacondones of Naha.'
date: 2020-09-17
venue: 'Journal of Folklore Research Reviews'
paperurl: 'https://jfr.sitehost.iu.edu/review.php?id=2498'
citation: 'Campbell, Sarah Alice. (2020). &quot;Review of Xurtan: The End of the World and Other Myths, Songs, Charms, and Chants by the Northern Lacondones of Naha by Suzanne Cook.&quot; <i>Journal of Folklore Research Reviews</i>. https://jfr.sitehost.iu.edu/review.php?id=2498.'
---

A review of Suzanne Cook's Xurtan The End of the World and Other Myths, Songs, Charms, and Chants by the Northern Lacondones of Naha.

[Read the review here](https://jfr.sitehost.iu.edu/review.php?id=2498)

Recommended citation: Campbell, Sarah Alice. (2020). "Review of <i>Xurt'an: The End of the World and Other Myths, Songs, Charms, and Chants by the Northern Lacondones of Naha<i> by Suzanne Cook." <i>Journal of Folklore Research Reviews</i>. https://jfr.sitehost.iu.edu/review.php?id=2498.`

**Comment by ifeomaozo** [comment]
Try changing the "https" to "http". That worked for me for some reason.

**Comment by minjechoi** [comment]
I'm having the same issue, the first paper I changed works but none of the latter ones.

**Comment by gvieralopez** [comment]
I have the same issue in 2 of my publications:

https://github.com/gvieralopez/gvieralopez.github.io/blob/master/_publications/4.md
https://github.com/gvieralopez/gvieralopez.github.io/blob/master/_publications/6.md

Nothing of the above solved the problem. I think it is related to breaking markdown rules (because even the preview of github looks different in those 2 publications), but I can't find where the problem is. I have tried a lot of different tests, but no result.

**Comment by cmoserj** [comment]
> I'm having the same issue, the first paper I changed works but none of the latter ones.
> 
> (update) I noticed that in my citation column my string started and ended using ' ' but I also had a ' in the middle of the text (e.g., WWW'20). Fixing that line made the whole item appear.

After spending hours trying to fix this one issue, this did it for me.
