### ISSUE TITLE
How to add a new page

### ISSUE THREAD

**Issue by abdullahyildiz** [academicpages/academicpages.github.io#50]
I'd like to create an off-topic page.

I created an _offtopic folder and add a few files under it. I also updated navigation.yml and created offtopic.html file.

When I want to access the files under _offtopic folder

```
{% include base_path %}

{% for post in site.offtopic reversed %}
  {% include archive-single.html %}
{% endfor %}
```

the page looks empty.

How can I fix this?

**Comment by wAuner** [comment]
any luck? I also tried to rename a page. However if I rename it, the site can't be found anymore. I renamed the _portfolio dir,  navigation.yml and also _pages/portfolio.html. Anything else?

**Comment by xuewenyuan** [comment]
have you solved this? I have the same question.

**Comment by abdullahyildiz** [comment]
Somehow I solved my problem but now I couldn't remember how I did it.

**Comment by xuewenyuan** [comment]
@abdullahyildiz anyway, thanks for your reply. I solved just now.

**Comment by fangzhou-xie** [comment]
I have the same problem now... I wonder how did you guys manage to solve this? @xuewenyuan @abdullahyildiz

**Comment by fangzhou-xie** [comment]
Aha! I found the solution. For those who will see this in the future, I need to update the `collections` and `defaults` fields in the `_config.yaml` file.

**Comment by Nalydz** [comment]
thanks for  your solution, I got it!

**Comment by Nalydz** [comment]
thanks for your solution, I got it! @fangzhou-xie
