### ISSUE TITLE
Cannot embed PDF on CV tab

### ISSUE THREAD

**Issue by ashleymaeconard** [academicpages/academicpages.github.io#502]
Hello, I have enjoyed using academicpages! 

I am able to add a pdf within the "about me" tab but I cannot do that within CV. Can you please tell me how to do this? I have been searching through various scripts but cannot seem to find how to fix this. 

Also, is there an easy way to add another icon and link to the _config.html file? I would like to add my Spotify profile.

Thank you! 
Ashley

**Comment by ritzdevp** [comment]
Try using this line of code. It worked for me!
In `_pages/cv.md`, paste this
`<embed src="{{ site.baseurl }}/files/yourdoc.pdf" width="600" height="700" type='application/pdf'>
`
Make sure your required doc is in the 'files' folder.
