### ISSUE TITLE
How do we change the indentation in code highlight?

### ISSUE THREAD

**Issue by tdincer** [academicpages/academicpages.github.io#511]
The indentation is 2 spaces for tab in my code highlights. Is it possible to set the default tab value to 4 spaces?

**Comment by zheyuye** [comment]
Perhaps you can do some changes here https://github.com/academicpages/academicpages.github.io/blob/25c30de2b4ce3e3f23559384699bb4b9865d6473/_sass/_syntax.scss#L31-L32
