### ISSUE TITLE
Remove avatar white wash? 

### ISSUE THREAD

**Issue by SapanaChaudhary** [academicpages/academicpages.github.io#526]
The avatar rendered on webpage seems to be white washed. How can I remove this feature? 
I would like avatar to have the original image color all the time, and not just while hovering over it.  

Thank you.

**Comment by chuanzhidong** [comment]
> The avatar rendered on webpage seems to be white washed. How can I remove this feature? I would like avatar to have the original image color all the time, and not just while hovering over it.
> 
> Thank you.

I also have the same problem. Did solve it?
Thanks

**Comment by SapanaChaudhary** [comment]
Oh no, I couldn't find a way to do it.

**Comment by SapanaChaudhary** [comment]
I figured it out. 
The opacity value should be 1 here https://github.com/academicpages/academicpages.github.io/blob/25c30de2b4ce3e3f23559384699bb4b9865d6473/_sass/_sidebar.scss#L18

Thanks!

**Comment by chuanzhidong** [comment]
> 

It works! Thank you so much!!

**Comment by rjzupkoii** [comment]
Closing since it appears that this was removed from the template.
