### ISSUE TITLE
Markdown emojis not rendering on webpage

### ISSUE THREAD

**Issue by mertall** [academicpages/academicpages.github.io#534]
Hello, I am trying to utilize markdown emojis. When I insert an emoji as ':_emoji_title_:' it renders in markdown preview but does not display on my site, rather only comes out as the character values on the webpage.

**Comment by YicongHong** [comment]
same question here

**Comment by rjzupkoii** [comment]
It looks like this is referring to extended emoji like [the ones in this list](https://gist.github.com/rxaviers/7360908) - those don't appear to be part of the basic Markdown installation so I'll have to see how to enable them.
