### ISSUE TITLE
Sass 4.0 deprecated function call.

### ISSUE THREAD

**Issue by DannieBGoode** [academicpages/academicpages.github.io#54]
when running `jekyll serve` I get the following warnings:
`DEPRECATION` WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("variable-exists")) instead.`

This was reported in the original minimal mistakes them and fixed, check [here](https://github.com/mmistakes/minimal-mistakes/issues/1114).

**Comment by hanlonmt** [comment]
Is there any plan to get a fix for this? I'd like to use this template to build a new webpage, but I'm reluctant if there's a soon-to-be deprecation

**Comment by ankitshah009** [comment]
Unable to fix the issue via the post mentioned on minimal mistakes 
Need more steps how to fix the issue.

**Comment by st-dimopoulos** [comment]
As I mentioned in the closed issue referenced above, in the Minimal Mistakes theme this was fixed by upgrading susy (see [here](https://github.com/mmistakes/minimal-mistakes/issues/1114)). Can this be done to this fork too?

**Comment by rjzupkoii** [comment]
This appears to have been addressed with the latest updates.
