### ISSUE TITLE
How to make social media and e-mail link in left sidebar (below the name and bio)

### ISSUE THREAD

**Issue by jehoonchae** [academicpages/academicpages.github.io#540]
The title says it all.
I want to add Twitter, GitHub, and email links to the sidebar. But it does not work even write the URL of the social media profile in _config.yml.  
Is there anyone who knows how to?

**Comment by marcfehling** [comment]
I see that you managed to get it to work on your personal website. This can be closed then?

**Comment by jehoonchae** [comment]
Ah yes, thank you!
