### ISSUE TITLE
How to enable google anlalytics?

### ISSUE THREAD

**Issue by Yongyao** [academicpages/academicpages.github.io#55]
First of all, thank you for this excellent template. I just customized it to my own need (https://yongyao.github.io/). One thing I want to ask is what is the best way to enable google analytics or any other type of watching function in this template? I saw there is an analytics folder in the code base.

**Comment by pswpswpsw** [comment]
My way of doing this might not be optimal. A few years ago what I did is simply put the url of my main page in google analytics. So I didn't do anything on weebly side (although I should add source code like https://hc.weebly.com/hc/en-us/articles/201979698-Google-Analytics). Still things are working on google analytics for all of my basic need.

Btw, your website is very awesome so I forked it to build mine.

**Comment by biona001** [comment]
Inside _config.yml there is an analytics section (with default "google-universal").

Adding my google analytics ID in brackets "UA-XXXXXXXXX-X" works.

**Comment by Yongyao** [comment]
Great! It works like a charm

**Comment by Stephaniedroop** [comment]
> Inside _config.yml there is an analytics section (with default "google-universal").
> 
> Adding my google analytics ID in tracking_id field like "UA-XXXXXXXXX-X" works.

Btw, is it stream ID or measurement ID that I add to the tracking_id field?
