### ISSUE TITLE
How to add new section to _data/navigation.yml

### ISSUE THREAD

**Issue by shbrainard** [academicpages/academicpages.github.io#560]
I created a new element in the navigation YAML:

  - title: "Software"
    url: /software/

and a new directory in root "_software" with .md files containing descriptions of software projects I've developed.

Clicking on the "Software" link in the navigation bar, however, returns the 404 page.  What are the steps to getting this HTML to be generated.

Thanks!

**Comment by seralouk** [comment]
I used:

  - title: "Contact"
    url: /contactme/

and then inside _pages I put my .md

**Comment by Nalydz** [comment]
you need to add something  incollections and defaults in _config.yml
