### ISSUE TITLE
How to add multilingual contents in this site

### ISSUE THREAD

**Issue by argyili** [academicpages/academicpages.github.io#568]
Like a button to change language from English to Chinese or Japanese. (Of course, the practical content is edited by myself.)

**Comment by mikedenly** [comment]
What I did was go to _config.yml (use Sublime Text or Atom to edit it), and change the locale. I frequently type in French, Spanish, and Italian, so I changed the locale to "es-ar" (i.e., Spanish: Argentina), and that allowed me to start typing in all of the accents on my pages without getting errors. I am sure that someone more experienced might know of a better solution, but that worked for me.
