### ISSUE TITLE
Academicpages website not appearing in google search result

### ISSUE THREAD

**Issue by aanand300** [academicpages/academicpages.github.io#573]
Hi everyone,

My academic pages website is up and running but it does not appear on google search. Can anyone please suggest ways to improve the visibility of the website on google?
Any help or guidance is much appreciated.

Thanks in advance.

**Comment by mikedenly** [comment]
Mine took about a week to show up after following instructions here: https://support.google.com/webmasters/answer/34397?hl=en

**Comment by mikedenly** [comment]
It takes a week or two for Google to find your website and start crawling after you follow the instructions from the link that I provided above. It is unfortunately necessary to be patient. You cannot get Google to find your website immediately. I don't know anything about an html file.

**Comment by seralouk** [comment]
> It takes a week or two for Google to find your website and start crawling after you follow the instructions from the link that I provided above. It is unfortunately necessary to be patient. You cannot get Google to find your website immediately. I don't know anything about an html file.

I used the link that you posted and then I entered my URL and clicked verify. Next, I get some options like to upload an HTML file on my website in order to get verified..

**Comment by chengzhang17** [comment]
> > It takes a week or two for Google to find your website and start crawling after you follow the instructions from the link that I provided above. It is unfortunately necessary to be patient. You cannot get Google to find your website immediately. I don't know anything about an html file.
> 
> I used the link that you posted and then I entered my URL and clicked verify. Next, I get some options like to upload an HTML file on my website in order to get verified..

Just upload the HTML file to the master file (the file where README.md is)

**Comment by seralouk** [comment]
> > > It takes a week or two for Google to find your website and start crawling after you follow the instructions from the link that I provided above. It is unfortunately necessary to be patient. You cannot get Google to find your website immediately. I don't know anything about an html file.
> > 
> > 
> > I used the link that you posted and then I entered my URL and clicked verify. Next, I get some options like to upload an HTML file on my website in order to get verified..
> 
> Just upload the HTML file to the master file (the file where README.md is)

Can you explain exactly what you mean? To upload into the GitHub repository the HTML file that I get from Google for verification?

**Comment by chengzhang17** [comment]
> > > > It takes a week or two for Google to find your website and start crawling after you follow the instructions from the link that I provided above. It is unfortunately necessary to be patient. You cannot get Google to find your website immediately. I don't know anything about an html file.
> > > 
> > > 
> > > I used the link that you posted and then I entered my URL and clicked verify. Next, I get some options like to upload an HTML file on my website in order to get verified..
> > 
> > 
> > Just upload the HTML file to the master file (the file where README.md is)
> 
> Can you explain exactly what you mean? To upload into the GitHub repository the HTML file that I get from Google for verification?

Yes. You get an HTML file from google. Then you upload the file to the GitHub repository. Make sure you can open the file via the following link:

yourname.github.io/googlefilename.html
