### ISSUE TITLE
Google scholar link points at author.uri

### ISSUE THREAD

**Issue by aitorshuffle** [academicpages/academicpages.github.io#6]
Hi,

Many thanks for sharing this super-userful template! Just found that the Google Scholar link in the sidebar doesn't point to the google scholar profile introduced in the `googlescholar` field in `_config.yml`, but to the  content of `author.uri` (seen in `_includes/author-profiles.html` line 104). Shouldn't this be `author.googlescholar` instead?

**Comment by staeiou** [comment]
Good catch! Fixed in 34bd699
