### ISSUE TITLE
Where to modify sidebar and How to remove sitemap

### ISSUE THREAD

**Issue by unknownxu1990** [academicpages/academicpages.github.io#66]
I want to show my email address not just a link, but also I want the whole address appears on the website as well. Also, I'm wondering how to hide the sitemap at the bottom of the webpage. Thanks for the help.

**Comment by astrojt** [comment]
I would also like to know how to remove the sitemap link from the bottom of the webpage.

**Comment by AntoineSoetewey** [comment]
In the file custom.html @astrojt

**Comment by astrojt** [comment]
Thank you so much! @AntoineSoetewey

**Comment by chengniedotcom** [comment]
How to modify this section to display the email in text?

`        <li><a href="mailto:{{ author.email }}"><i class="fas fa-fw fa-envelope" aria-hidden="true"></i> {{ site.data.ui-text[site.locale].email_label | default: "Email" }}</a></li>`

Also, Is there a way to "hide" the email using html coding instead?

<p>Please email us at 
<a href="&#109;&#097;&#105;&#108;&#116;&#111;:&#101;&#120;&#097;
&#109;&#112;&#108;&#101;&#055;&#064;&#104;&#101;&#097;&#114;&#116;
&#105;&#110;&#116;&#101;&#114;&#110;&#101;&#116;&#046;&#117;&#107;">
&#101;&#120;&#097;&#109;&#112;&#108;&#101;&#055;&#064;&#104;&#101;
&#097;&#114;&#116;&#105;&#110;&#116;&#101;&#114;&#110;&#101;&#116;
&#046;&#117;&#107;</a>.</p>

**Comment by jinlx** [comment]
Could you anyone give more insights on removing the sitemap and feed at the bottom?
