### ISSUE TITLE
Avatars: only the test images work

### ISSUE THREAD

**Issue by jroeder-astro** [academicpages/academicpages.github.io#692]
I know there is an old thread about this but is appears to be dormant. I can set the given avatars such as 500x300.png or bio-photo-2.jpg just fine. My own images, in the same folder, do not work. They simply do not show up, neither after pushing nor with local build. I just get an empty ellipse with again my name in it. I have tried all solutions provided in the previous thread but I am out of options. The path is working as "500x300.png" for example, so no longer path required. Just with my own images, no chance. I will greatly appreciate all help.

**Comment by vishaln15** [comment]
Your avatar can be any `.png` or even `.JPG` file. I believe your problem lies with `url` and `baseurl` path. I experienced the same problem and I found that setting an empty string for `baseurl` and filling in `https://username.github.io` in `_config.yml` worked for me. Essentially, 
```
url: https://username.github.io
baseurl: ""
```

**Comment by Zijia-Cheng** [comment]
Hi, I wonder is there a way to change the size and position of a image in the webpage through markdown file? Thanks!

**Comment by shruthi-venkatesh** [comment]
I'm having the same issue, and I've set my url and baseurl as above. Any help would be greately appreciated.
