### ISSUE TITLE
Cropped Table of content

### ISSUE THREAD

**Issue by YonSci** [academicpages/academicpages.github.io#706]
Hi, there, I was deploying a table of content on one of the pages but the resulting toc on the page is not showing the whole content, it is somehow cropped as seen below:

https://github.com/YonSci/yon_academic/blob/master/images/toc.jpg

What should I do to fix this issue?

**Comment by lzkelley** [comment]
Same issue

**Comment by lzkelley** [comment]
I believe this is the same as [this issue](https://github.com/academicpages/academicpages.github.io/issues/221).
The solution I found is [described here](https://github.com/academicpages/academicpages.github.io/issues/221#issuecomment-1819606138).
