### ISSUE TITLE
Font size for code in markdown

### ISSUE THREAD

**Issue by anlijuncn** [academicpages/academicpages.github.io#715]
Hi, Thanks for this useful repo! 

I built one website based on this repo (https://anlijun.cn) successfully. However, I found if I use ``` code``` (three single apostrophes) to write in a markdown file, the font size in the webpage would be very small. 

You can check this [post](https://anlijun.cn/posts/2021/08/VectorizedMultiVariableIntegral/) for example, I also put a screen shot for fast check. 
![image](https://user-images.githubusercontent.com/38600288/129192577-9dc08a47-4e9f-41b8-a31a-05be0d955665.png)

Do you know how to fix this? 

Thanks for your help!

**Comment by aoguedao** [comment]
Hi @anlijuncn! Could you fix it? I have the same issue

**Comment by anlijuncn** [comment]
Unfortunately I didn’t fix it

**Comment by aoguedao** [comment]
Hi! You could try modifying `font-size`  on the file `sass/_syntax.scss`.  I modified both to `$type-size-5` because I have no idea of html and css. It works so I won't fixed haha

**Comment by anlijuncn** [comment]
Thanks! I will try your solution.
