### ISSUE TITLE
If I modify my GitHub username, is it possible for me to continue using this personal page?

### ISSUE THREAD

**Issue by HelloWorldLTY** [academicpages/academicpages.github.io#747]
If I change my GitHub username, I found that my personal page display incorrectly and even disappeared. Are there any solutions? Thanks.

**Comment by ChineseBest** [comment]
Any ideas? Thanks.

**Comment by vishaln15** [comment]
Hey @HelloWorldLTY , update the following key-value in _config.yml and I think you should be good to go.
1. "url"
2. "repository"
3. "github"
