### ISSUE TITLE
Blog post link not appearing

### ISSUE THREAD

**Issue by snehjp2** [academicpages/academicpages.github.io#763]
Hi,

Trying to upload a new blog post and the link/title is not showing up.  I've just been copy and pasting code from previous posts and modifying them, so not sure what's going wrong with this one.  The .md file naming follows the convention and the permalink is formatted correctly, triple checked. The post is uploaded but I can't access it via link, also the path is using the .md file naming instead of the set permalink path. Anyone have any suggestions?

![Screen Shot 2021-10-30 at 9 46 27 PM](https://user-images.githubusercontent.com/47462873/139563339-9faaab52-1506-4764-9033-47d945033946.png)

**Comment by YikeShen** [comment]
I came across the same problem. I added at the exact same format, however, the blog wasn't showing in my website.

**Comment by zpparks314** [comment]
Did you ever fix this? @snehjp2
