### ISSUE TITLE
How to remove the footer ?

### ISSUE THREAD

**Issue by liming-ai** [academicpages/academicpages.github.io#781]
How to remove the footer ?

**Comment by philsf** [comment]
See if this helps: https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-footer

**Comment by mitming** [comment]
> See if this helps: https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-footer

Thanks a lot!

**Comment by rjzupkoii** [comment]
If RSS is disabled and the user does not have a GitHub or Bitbucket account, the "Follow" line in the footer is automatically removed by the template.
