### ISSUE TITLE
Way to add blogger icon and link easily?

### ISSUE THREAD

**Issue by ashleymaeconard** [academicpages/academicpages.github.io#784]
Hi! 

You have a great layout for siting author work for websites like LinkedIn, Google Scholar, and even keybase. Do you have something for https://www.blogger.com/? Is there a resource you could point me to to quickly add this feature if not? Should there not be a quick solution I can figure it out. 

Thank you for a great framework! 
Ashley

**Comment by EdOverflow** [comment]
In your `_config.yml`, add a `blogger:` entry under `author:`.

```yaml
author:
...
  blogger          : "..."
...
```

Then, under `_includes/author-profile.html`, add the following among the list of author URLs:

```
{% if author.blogger %}
    <li><a href="{{ author.blogger }}"><i class="fab fa-fw fa-blogger"></i> Blogger</a></li>
{% endif %}
```

You should end up with a Blogger icon linking to your Blogger page.

<img src=https://user-images.githubusercontent.com/18099289/145686980-47a1c624-f9e3-4a20-b25b-f7010a45d4d1.png width=220px>

**Comment by ashleymaeconard** [comment]
Thank you that works perfectly.

**Comment by ashleymaeconard** [comment]
Thank you that works perfectly.
