### ISSUE TITLE
How to change the background color of the drop down menu under the "Follow" button?

### ISSUE THREAD

**Issue by jasonlin316** [academicpages/academicpages.github.io#790]
<img width="183" alt="screenshot 2021-11-23 下午10 13 04" src="https://user-images.githubusercontent.com/35606918/143184673-3700e04b-9301-4217-89b5-acd0a2acd434.png">

When browsing on a small screen, the Follow button appears and shows a drop down menu if clicked on the button. I have changed the theme color manually, but failed to change the background color of the drop down menu showing email, LinkedIn, etc. Where can I change that background color? Thanks.

**Comment by jwb4335** [comment]
Go to this line, and you can change the color of the dropdown menu:

https://github.com/academicpages/academicpages.github.io/blob/25c30de2b4ce3e3f23559384699bb4b9865d6473/_sass/_sidebar.scss#L170
