### ISSUE TITLE
Images not showing in blog _posts

### ISSUE THREAD

**Issue by JayanthRR** [academicpages/academicpages.github.io#80]
I am looking to add images in my blog post. I placed the corresponding image in the `images/` folder and included the following line in markdown file in `_posts/`. 
`![](../images/DP1.png)`

I am able to see the image in my atom editor, but when I push the changes and refresh the webpage, I do not see it in the blog. Any idea how to resolve this?
Note: I even tried placing the image in the `_posts/` directory and modified the line to
`![](DP1.png)`
but it doesn't work.

**Comment by litingfeng** [comment]
I had the same issue

**Comment by JayanthRR** [comment]
Hey,

I don't think that issue is sorted and I no longer use academic pages, I
had other issues and finally decided to use Hugo.

Thanks and regards,
Jayanth.

**Comment by litingfeng** [comment]
Thanks, I think I should consider switching to other framework too.

**Comment by zotroneneis** [comment]
I'm having the same issue. Is there any progress or idea yet?

**Comment by sar-gupta** [comment]
> ![](/images/DP1.png)
and you're good to go!

**Comment by drdh** [comment]
Hi, I find another solution https://github.com/academicpages/academicpages.github.io/issues/140#issuecomment-508975941

**Comment by rlucas7** [comment]
https://github.com/academicpages/academicpages.github.io/issues/91#issuecomment-2427689676
^this comment is what fixed the issue for me, seems to work regardless of where you store the images
