### ISSUE TITLE
Is there a way to add a direct link in navigation.yml?

### ISSUE THREAD

**Issue by ehsong** [academicpages/academicpages.github.io#824]
For instance, I want to link an external site to one of the menus in nvigation.yml. How can I add this?

**Comment by salbalkus** [comment]
For future reference, I just tried this myself; all you need do is add your link in navigation.yml with the external site listed as the url. So for example, adding:

```
  - title: "Your Title Here"
    url: https://github.com/academicpages/academicpages.github.io/issues/824
```
to navigation.yml (under the _data folder) would add an item to the nav bar that links to the given url.
