### ISSUE TITLE
Put Lasted Updated Date in the footer

### ISSUE THREAD

**Issue by chengniedotcom** [academicpages/academicpages.github.io#828]
Is there a way to show something like "Last updated: 2021 Dec 23" in the footer? I mean to insert the date when the code was pushed to github.

**Comment by chengniedotcom** [comment]
I found a way to do it manually. For example, in the `footer.html` just add:
`Last Updated: 2021 Dec 31`

**Comment by samiran-kawtikwar** [comment]
How can we make the date change automatically? 
I tried site.time but that is the live time and not the time when it was updated.
page.time and page.date do not work.

**Comment by rjzupkoii** [comment]
While not quite as good as the date each page was updated, this might be as good as we can get for the time being. Updated the template with a "Site last updated" field in the footer.
