### ISSUE TITLE
Is it possible to play a mp4 video?

### ISSUE THREAD

**Issue by chengniedotcom** [academicpages/academicpages.github.io#829]
I tried this, but it does not seem to play the video:
`[![Video]](/files/video.mp4)`

**Comment by vishaln15** [comment]
I don't think `.mp4` files work on markdown. However, you can convert the video into a `.gif` file which does work in markdown. Check it out!

**Comment by chengniedotcom** [comment]
Thanks for the work-around. Another way I found is to upload the video to Youtube and then embed the youtube link following:  https://support.google.com/youtube/answer/171780?hl=en

**Comment by milankl** [comment]
There is no problem using html in markdown and include a line like
```
<video src="https://raw.githubusercontent.com/github_username/github_username.github.io/main/files/video.mp4" controls="controls" style="max-width: 700px;">
</video>
```
where you upload the .mp4 into `/files` in your repository (or any other path)
