### ISSUE TITLE
Changes to *.sass files do not apply when trying to run locally.

### ISSUE THREAD

**Issue by somso2e** [academicpages/academicpages.github.io#830]
For some reason when you change a variable or something in a *.scss file it doesn't compile to *.css and changes don't apply on the localhost. But if you push it, it works fine and you can see the changes on the actual website.

**Comment by Samir-Rashid** [comment]
Your webpage is trying to download the main css file from your domain rather than localhost, which contains the modified files. See #830

**Comment by somso2e** [comment]
hi @Samir-Rashid, thanks for the response but **this** issue is #830... :smile:

**Comment by Samir-Rashid** [comment]
My mistake. I meant #313. The fix is to just set the domain to localhost as you develop.
