### ISSUE TITLE
'_config.yml' future: false not working

### ISSUE THREAD

**Issue by CindyChow123** [academicpages/academicpages.github.io#834]
The "future" field in "_config.yml" is supposed to be used to hide future posts when set to false. However, this cannot be done in my forked project.

**Comment by rjzupkoii** [comment]
Appears to be the same issue as #53, if you can provide some more details on reproducing the bug I might be able to fix it, but as of now I can't seem to replicate it.

**Comment by rjzupkoii** [comment]
It's been over two weeks with no updates, so I'm going to go ahead and close this issue as unreproducible.
