### ISSUE TITLE
Bigger picture & wider sidebar?!

### ISSUE THREAD

**Issue by FastLump** [academicpages/academicpages.github.io#842]
Hi Stuart and other friendly people that might be able to help me out here,

I've been trying to adjust the size of the picture for a whlie now, and while I have found some hints in the issues, I haven't been able to succeed. I am imagining putting a significantly larger picture (square) in the sidebar. I have been playing around with the _sidebar.scss file a bunch, but somehow neither succeeded in getting the picture to be a square, nor for it to get larger.

Now, when uploading a very skinn, vertically long picture I have been managing to get it to be quite large -- so I presume the issue with width is related to the size of the sidebar. Does that sound right? And if so, how do I make the sidebar wider?

Second, how do I get the picture to be square and without the border? I tried copying out the border-radious line that somebody suggested on here but that didn't change anything.

Any help would obviously be highly appreciated and loving the template :)

**Comment by serenayj** [comment]
I have the same question. Any help will be greatly appreciated!

**Comment by yukimuon** [comment]
Hi, you can change the sidebar width here, when specified in each screen size (x-large, large, etc.) https://github.com/academicpages/academicpages.github.io/blob/25c30de2b4ce3e3f23559384699bb4b9865d6473/_sass/_sidebar.scss#L28
Just add a width property and it would work.

**Comment by aranyac** [comment]
Any examples of this?

**Comment by sam-lindquist** [comment]
I'm don't know how to change the side bar size, but I was able to change the shape of the photo by editing `border-radius`. I believe `border-radius: 0%` would give a regular square. In my case, I did `border-radius: 10%` , which gives a square with rounded edges.

**Comment by rjzupkoii** [comment]
Information for adjusting the sidebar [can be found in the wiki](https://github.com/academicpages/academicpages.github.io/wiki/Customizing-the-layout-of-your-site#adjusting-the-sidebar).
