### ISSUE TITLE
Google scholar link in publications doesn't work

### ISSUE THREAD

**Issue by taranu** [academicpages/academicpages.github.io#862]
It looks like there's supposed to be a link to Google Scholar at the top of the publications page (granted, it's redundant with the sidebar link, but still):

https://github.com/academicpages/academicpages.github.io/blob/master/_pages/publications.md?plain=1#L8

However, this doesn't show up on the page even if `author.googlescholar` is defined (as it is in the template):

https://academicpages.github.io/publications/

**Comment by profgavinbrown** [comment]
Any update on this? It seems none of the author.X variables are visible in the pages…

**Comment by abhcs** [comment]
Use `site.author.googlescholar` instead.

**Comment by rjzupkoii** [comment]
Resolved by pull request #925
