### ISSUE TITLE
How to change the order of itmes in Portfolio page

### ISSUE THREAD

**Issue by Logenleedev** [academicpages/academicpages.github.io#870]
I want to put the most updated work on the top of the page, but right now the order is reversed. Is there any way to fix this?

**Comment by ross-dobson** [comment]
I'd be interested to know if there was a way to do this. In `_config.yml` I have tried defining an order list, and tried having them sorted by a key/value in the front matter (as shown in [the Jekyll docs for collections](https://jekyllrb.com/docs/collections/), but none of this has worked.
