### ISSUE TITLE
references

### ISSUE THREAD

**Issue by KamilSJaron** [academicpages/academicpages.github.io#9]
Hello, I was wondring if there is an elegant way how to add references in the text. So far I am just using hyperlinks to DOIs, but that is not optimal. I found some [bibtex flavoured markdowns](http://www.chriskrycho.com/2015/academic-markdown-and-citations.html), another solution that I find quite ok is though [footnotes](http://rephrase.net/box/word/footnotes/syntax/). 

Is there a way how to make scientific references in your template?

P.S. Thanks a lot, it is a great template. I am playing it continuously for last four days (you can check out my webpage!).

**Comment by rjzupkoii** [comment]
Markdown footnotes were added to the template which seems to meet the requirements for this issue.
