### ISSUE TITLE
How to change the sitemap?

### ISSUE THREAD

**Issue by FelixStips** [academicpages/academicpages.github.io#910]
I have not used the structure of academicpages with the different collections "publication" "research" "teaching" and "blog". Rather I created unformatted pages and inserted the information there directly. The problem is that now the sitemap does not align with my website, and since google looks for the sitemap it finds the site "publications" which is empty, rather than my landing page. How can I manually change the sitemap to align with my structure?

Or easier question, where is the sitemap file or the file that creates the sitemap file?

**Comment by XiaoxiaoSun0321** [comment]
you can change it at the navigation.yml file
