### ISSUE TITLE
page navigator not showing up on mobile 

### ISSUE THREAD

**Issue by dkoen** [academicpages/academicpages.github.io#913]
For some reason the page navigator in the top right is invisible. If I tap there it brings up a drop down. I am not sure where the code is to edit the default appearance of the mobile drop down. Can someone help point me in the right direction?

**Comment by leclere** [comment]
Same problem: the page navigator does not shows on mobile, which is troublesome for student looking for info on classes for example.

**Comment by rjzupkoii** [comment]
I'm unable to reproduce this on my iPhone, which browser are you using?

**Comment by rjzupkoii** [comment]
This sounds like it might be the same as #1920 - I'm going to go ahead and close this issue since addressing that one *might* fix this issue and it also appears that both of the commenters are inactive.
