### ISSUE TITLE
ERROR NoMethodError: undefined method `key?` for nil:NilClass in `conditionally_inject_charset`

### ISSUE THREAD

**Issue by bstee615** [academicpages/academicpages.github.io#943]
First off, thank you for providing/maintaining this awesome template.

My fork works very well when serving on Windows and on github pages. But when I try to run my site on Linux (Ubuntu 20.04.1), I get an error on GET requests: "ERROR NoMethodError: undefined method `key?` for nil:NilClass" in function `conditionally_inject_charset`. This makes it so that the website always shows up with "page not found".

I searched for this error message, but it seems to be pretty broadly applicable so I couldn't find a solution. Can you help me figure out how to fix the error?

To provide a simple reproduction of the error, I ran the original repository at academicpages.github.io and found that the same problem occurs on both my fork and the original repo. The problem is detailed below.

I'm running on Ubuntu 20.04.1. I installed `ruby` and `bundle` using the command from the README:
```bash
sudo apt install ruby-dev ruby-bundler nodejs
```

Here is the transcript of the terminal. I also attached a full transcript from install to liveserve in [transcript.txt](https://github.com/academicpages/academicpages.github.io/files/8929339/transcript.txt).

```bash
(base) benjis@AM:~/code/academicpages.github.io$ bundle exec jekyll liveserve
Configuration file: /home/benjis/code/academicpages.github.io/_config.yml
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
            Source: /home/benjis/code/academicpages.github.io
       Destination: /home/benjis/code/academicpages.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
                    done in 7.459 seconds.
 Auto-regeneration: enabled for '/home/benjis/code/academicpages.github.io'
Configuration file: /home/benjis/code/academicpages.github.io/_config.yml
 LiveReload Server: 127.0.0.1:35729
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
[2022-06-17 09:41:18] ERROR NoMethodError: undefined method `key?' for nil:NilClass
	/home/benjis/code/academicpages.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve/servlet.rb:191:in `conditionally_inject_charset'
	/home/benjis/code/academicpages.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve/servlet.rb:176:in `do_GET'
	/home/benjis/code/academicpages.github.io/vendor/bundle/ruby/2.7.0/gems/hawkins-2.0.5/lib/hawkins/servlet.rb:134:in `do_GET'
	/usr/lib/ruby/2.7.0/webrick/httpservlet/abstract.rb:105:in `service'
	/usr/lib/ruby/2.7.0/webrick/httpservlet/filehandler.rb:233:in `service'
	/usr/lib/ruby/2.7.0/webrick/httpserver.rb:140:in `service'
	/usr/lib/ruby/2.7.0/webrick/httpserver.rb:96:in `run'
	/usr/lib/ruby/2.7.0/webrick/server.rb:307:in `block in start_thread'
```

And here is what the page looks like on the original repo:
![image](https://user-images.githubusercontent.com/22305849/174341227-ba6b045a-5579-47b4-a519-d2454e28842b.png)

And here is what it looks like on my work (should look like [benjijang.com](benjijang.com)):
![image](https://user-images.githubusercontent.com/22305849/174342531-a0b1d61e-e366-4b36-b372-f065d7cd95ae.png)

**Comment by bstee615** [comment]
I realized that my Windows box was running Jekyll 3.9.0 while my Linux box was running Jekyll 3.9.2 (latest 3.x version). After downgrading my Linux box to Jekyll 3.9.0, my fork and the original repo started working, and after upgrading my Windows box to Jekyll 3.9.2, my fork stopped working. Therefore, I believe Jekyll 3.9.2 is the reason for the failure. Not sure why, though.

My PR should fix the problem for any others encountering this issue.

**Comment by DavidLee528** [comment]
> 3.9.0

A useful solution for this problem, tried downgrade jekyll to 3.9.0 then problem disappeared. Great thanks😊

**Comment by XunshanMan** [comment]
If you are facing problem:
```
vendor/bundle/ruby/3.0.0/gems/pathutil-0.16.2/lib/pathutil.rb:502:in `read': no implicit conversion of Hash into Integer (TypeError)
```
Just change the version of jekyll ```3.9.0``` to ```3.9.3```:

In your Gemfile:
```
gem "jekyll", "3.9.3"
```

**Comment by yoyo115956** [comment]
> I realized that my Windows box was running Jekyll 3.9.0 while my Linux box was running Jekyll 3.9.2 (latest 3.x version). After downgrading my Linux box to Jekyll 3.9.0, my fork and the original repo started working, and after upgrading my Windows box to Jekyll 3.9.2, my fork stopped working. Therefore, I believe Jekyll 3.9.2 is the reason for the failure. Not sure why, though.

This really helped me to solve the problem, thanks so much, it's really so delightful that the web page is displaying properly!

**Comment by rjzupkoii** [comment]
This appears to be addressed with the latest updates.
