### ISSUE TITLE
Square Profile Picture Sidebar

### ISSUE THREAD

**Issue by kaanolgu** [academicpages/academicpages.github.io#952]
Is it possible to make the sidebar image rectangular ? Thanks!

**Comment by wvirany** [comment]
Hi @kaanolgu,

I know this was some time ago, but can you explain how you achieved this? Thanks

**Comment by rjzupkoii** [comment]
@wvirany Since this is a closed issue it's going to get very little attention, you may want open a new discussion topic, or create a new issue concerning this question.
