### ISSUE TITLE
Possible to use pipe character "|" for title_separator?

### ISSUE THREAD

**Issue by amyzlc** [academicpages/academicpages.github.io#969]
In _config.yml, I tried to edit the title_separator in the site settings to the pipe character "|", but it doesn't seem to work (it doesn't break anything, just nothing shows up).

Is there any way to get the pipe character to work for this? I'm guessing it's something to do with Liquid, but I'm unsure what's going on or if there's a way to "escape" the character.

**Comment by rjzupkoii** [comment]
Apparently this is a known issue (see jekyll/jekyll-seo-tag/issues/410) and while the pipe character - | - will not render correctly, if you assign HTML symbol entity of `&#124;` to the `title_separator`, i.e.,:

```yaml
title_separator          : "&#124;"
```

Then it will render correctly.
