### ISSUE TITLE
page build and deployment failed

### ISSUE THREAD

**Issue by MartineMathieu** [academicpages/academicpages.github.io#974]
Hello,

I'm getting an "page build and deployment" error each time I'm trying to update a file. It looks like the issue is from "Build with Jekyll. What can I do to solve it?

**Comment by BenQuigley** [comment]
Can you post the error?

**Comment by ehosseiniasl** [comment]
Hi
it also failed for me.

abort! time out error

**Comment by ehosseiniasl** [comment]
I just forked you repo and tried to deploy

https://github.com/ehosseiniasl/my-website.github.io

<img width="908" alt="Screen Shot 2022-10-05 at 2 19 29 PM" src="https://user-images.githubusercontent.com/6238049/194165875-55020226-1494-4b1f-ad7b-142179d9832d.png">
